window.toolCollections = window.toolCollections || {};
window.toolCollections.meme_factory = [
    {
        id: 'review_everything',
        name: '万物皆可测评',
        desc: '输入任意物品（如"路边的石头"），AI 生成一篇数码博主风的专业测评报告',
        href: 'tools/meme_factory/review_everything.html',
        icon: 'fa-solid fa-clipboard-check',
        category: 'meme_factory',
        tags: ['小红书', '抖音'],
        isNew: true,
        complexity: 1,
        iconBg: 'bg-purple-50',
        iconColor: 'text-purple-600',
        borderColor: 'purple-200',
        hoverTextColor: 'text-purple-600',
        linkColor: 'text-purple-600'
    },
    {
        id: 'animal_narrator',
        name: '动物世界解说器',
        desc: '输入你做的事，AI 模仿赵忠祥《动物世界》风格为你写一段解说词',
        href: 'tools/meme_factory/animal_narrator.html',
        icon: 'fa-solid fa-paw',
        category: 'meme_factory',
        tags: ['抖音', '短视频'],
        isNew: true,
        complexity: 1,
        iconBg: 'bg-green-50',
        iconColor: 'text-green-600',
        borderColor: 'green-200',
        hoverTextColor: 'text-green-600',
        linkColor: 'text-green-600'
    },
    {
        id: 'clickbait_converter',
        name: '震惊体转换器',
        desc: '输入任何事，AI 转成"震惊！不看后悔一辈子"的爸妈朋友圈爆款文体',
        href: 'tools/meme_factory/clickbait_converter.html',
        icon: 'fa-solid fa-bolt',
        category: 'meme_factory',
        tags: ['公众号'],
        isNew: true,
        complexity: 1,
        iconBg: 'bg-red-50',
        iconColor: 'text-red-600',
        borderColor: 'red-200',
        hoverTextColor: 'text-red-600',
        linkColor: 'text-red-600'
    },
    {
        id: 'argue_bot',
        name: 'AI 抬杠运动员',
        desc: '无论你说什么 AI 都疯狂找茬跟你抬杠。专治心情太好没人杠的毛病',
        href: 'tools/meme_factory/argue_bot.html',
        icon: 'fa-solid fa-comment-dots',
        category: 'meme_factory',
        tags: [],
        isNew: true,
        complexity: 1,
        iconBg: 'bg-orange-50',
        iconColor: 'text-orange-600',
        borderColor: 'orange-200',
        hoverTextColor: 'text-orange-600',
        linkColor: 'text-orange-600'
    },
    {
        id: 'billionaire_sim',
        name: '首富挥霍模拟器',
        desc: '拥有马斯克的资产，随便输入想买的东西，AI 算余额并评估你的挥霍水平',
        href: 'tools/meme_factory/billionaire_sim.html',
        icon: 'fa-solid fa-sack-dollar',
        category: 'meme_factory',
        tags: ['小红书', '抖音'],
        isNew: true,
        complexity: 1,
        iconBg: 'bg-yellow-50',
        iconColor: 'text-yellow-600',
        borderColor: 'yellow-200',
        hoverTextColor: 'text-yellow-600',
        linkColor: 'text-yellow-600'
    }
];
