window.toolCollections = window.toolCollections || {};
window.toolCollections.webtools = [
  {
    id: 'webtools_hub',
    name: 'Webtools 高频工具合集',
    desc: '包含 100+ 个高频生活与效率工具合集,涵盖时间管理、健康追踪、财务规划、实用工具、学习创作等场景。',
    href: 'tools/webtools/index.html',
    icon: 'fa-solid fa-table-cells',
    category: 'advanced_learning',
    tags: ['工具集', '效率工具'],
    isNew: true,
    iconBg: 'bg-indigo-50',
    iconColor: 'text-indigo-600',
    borderColor: 'indigo-200',
    hoverTextColor: 'text-indigo-600',
    linkColor: 'text-indigo-600',
    badgeStyle: 'bg-indigo-100 text-indigo-700'
  },
  // ================== 效率与时间管理 (Productivity) ==================
  { id: 'todo_list', name: '极简待办', desc: '高效的任务管理工具，支持分类、优先级与看板视图。', href: 'tools/webtools/todo_list.html', icon: 'fa-solid fa-check-square', category: 'webtools' },
  { id: 'pomodoro_timer', name: '专注番茄钟', desc: '沉浸式专注计时器，支持自定义时长与白噪音背景。', href: 'tools/webtools/pomodoro_timer.html', icon: 'fa-solid fa-timer', category: 'webtools' },
  { id: 'habit_tracker', name: '习惯养成打卡', desc: '热力图风格的习惯追踪，记录每一天的坚持与进步。', href: 'tools/webtools/habit_tracker.html', icon: 'fa-solid fa-activity', category: 'webtools' },
  { id: 'idea_box', name: '灵感便签 Box', desc: '卡片式灵感记录本，随时捕捉稍纵即逝的想法。', href: 'tools/webtools/idea_box.html', icon: 'fa-solid fa-lightbulb', category: 'webtools' },
  { id: 'gratitude_journal', name: '感恩日记', desc: '每天记录三件好事，培养积极乐观的心态。', href: 'tools/webtools/gratitude_journal.html', icon: 'fa-solid fa-heart', category: 'webtools' },
  { id: 'chore_tracker', name: '家务清单', desc: '分区管理家务事项，提升家庭整洁度与成就感。', href: 'tools/webtools/chore_tracker.html', icon: 'fa-solid fa-broom', category: 'webtools' },
  { id: 'countdown_days', name: '重要日子倒计时', desc: '铭记生活中的每一个重要时刻，支持自定义背景。', href: 'tools/webtools/countdown_days.html', icon: 'fa-solid fa-calendar-clock', category: 'webtools' },
  { id: 'game_tracker', name: '游戏时间追踪', desc: '记录游戏时长，统计游玩习惯与偏好。', href: 'tools/webtools/game_tracker.html',         icon: 'fa-solid fa-gamepad', category: 'webtools' },
  
  // ================== 生活与健康 (Life & Wellness) ==================
  { id: 'expense_tracker', name: '个人记账本', desc: '清晰的收支记录与图表分析，掌控个人财务状况。', href: 'tools/webtools/expense_tracker.html', icon: 'fa-solid fa-wallet', category: 'webtools' },
  { id: 'mood_journal', name: '心情气象台', desc: '记录每日情绪波动与日记，关注内心健康。', href: 'tools/webtools/mood_journal.html', icon: 'fa-solid fa-smile', category: 'webtools' },
  { id: 'water_tracker', name: '每日喝水助手', desc: '可视化的每日饮水记录，提醒保持健康水分。', href: 'tools/webtools/water_tracker.html', icon: 'fa-solid fa-droplet', category: 'webtools' },
  { id: 'breathing_exercise', name: '4-7-8 呼吸冥想', desc: '跟随视觉引导进行深呼吸，快速缓解焦虑与压力。', href: 'tools/webtools/breathing_exercise.html', icon: 'fa-solid fa-wind', category: 'webtools' },
  { id: 'period_tracker', name: '生理期记录', desc: '女性健康管理，预测生理期与排卵期。', href: 'tools/webtools/period_tracker.html', icon: 'fa-solid fa-heart', category: 'webtools' },
  { id: 'birthday_reminder', name: '生日提醒', desc: '记录亲友生日，倒计时提醒与星座计算。', href: 'tools/webtools/birthday_reminder.html', icon: 'fa-solid fa-cake', category: 'webtools' },
  { id: 'sleep_cycle', name: '睡眠周期计算', desc: '计算最佳入睡与唤醒时间，提升睡眠质量。', href: 'tools/webtools/sleep_cycle.html', icon: 'fa-solid fa-moon', category: 'webtools' },
  { id: 'weight_tracker', name: '体重趋势图', desc: '记录每日体重，自动生成 BMI 变化曲线。', href: 'tools/webtools/weight_tracker.html', icon: 'fa-solid fa-scale', category: 'webtools' },
  { id: 'workout_tracker', name: '运动打卡', desc: '记录运动时长与热量消耗，可视化运动习惯。', href: 'tools/webtools/workout_tracker.html', icon: 'fa-solid fa-dumbbell', category: 'webtools' },
  { id: 'meal_decider', name: '今天吃什么', desc: '随机选择餐点，拯救选择困难症。', href: 'tools/webtools/meal_decider.html', icon: 'fa-solid fa-utensils', category: 'webtools' },

  { id: 'pet_care', name: '宠物护理', desc: '记录爱宠的疫苗、驱虫与成长瞬间。', href: 'tools/webtools/pet_care.html', icon: 'fa-solid fa-paw-print', category: 'webtools' },
  { id: 'subscription_manager', name: '订阅管理', desc: '追踪 Netflix、Spotify 等长期订阅支出。', href: 'tools/webtools/subscription_manager.html', icon: 'fa-solid fa-credit-card', category: 'webtools' },
  { id: 'bill_tracker', name: '账单日历', desc: '管理房租水电等周期性账单，防止逾期。', href: 'tools/webtools/bill_tracker.html', icon: 'fa-solid fa-calendar-check', category: 'webtools' },
  { id: 'reading_log', name: '阅读记录', desc: '书架管理、阅读进度追踪与读书笔记。', href: 'tools/webtools/reading_log.html', icon: 'fa-solid fa-book', category: 'webtools' },
  { id: 'podcast_tracker', name: '播客追踪', desc: '记录听过的精彩播客单集与感悟。', href: 'tools/webtools/podcast_tracker.html', icon: 'fa-solid fa-headphones', category: 'webtools' },
  { id: 'vision_board', name: '愿景板', desc: '用图片拼贴出你的梦想与年度目标。', href: 'tools/webtools/vision_board.html', icon: 'fa-solid fa-image', category: 'webtools' },
  { id: 'bucket_list', name: '人生清单', desc: '列出你想做的 100 件事，并逐一实现。', href: 'tools/webtools/bucket_list.html', icon: 'fa-solid fa-mountain-snow', category: 'webtools' },
  { id: 'journal_prompts', name: '日记灵感', desc: '每日随机写作灵感，克服下笔困难症。', href: 'tools/webtools/journal_prompts.html', icon: 'fa-solid fa-pen-nib', category: 'webtools' },
  { id: 'digital_detox', name: '屏幕时间', desc: '数字排毒计时器，帮助你专注现实生活。', href: 'tools/webtools/digital_detox.html', icon: 'fa-solid fa-smartphone-off', category: 'webtools' },
  { id: 'mood_board', name: '情绪画板', desc: 'Year in Pixels 风格的年度情绪像素墙。', href: 'tools/webtools/mood_board.html', icon: 'fa-solid fa-grid', category: 'webtools' },
  
  // ================== 财务与投资 (Finance & Investment) ==================
  { id: 'loan_calculator', name: '房贷计算器', desc: '支持等额本息/本金，一键算出月供详情。', href: 'tools/webtools/loan_calculator.html', icon: 'fa-solid fa-calculator', category: 'webtools' },
  { id: 'compound_interest', name: '复利计算器', desc: '见证时间的玫瑰，预测长期投资回报。', href: 'tools/webtools/compound_interest.html', icon: 'fa-solid fa-trending-up', category: 'webtools' },
  { id: 'salary_visualizer', name: '工资可视化', desc: '五险一金与个税计算，看懂钱去哪了。', href: 'tools/webtools/salary_visualizer.html', icon: 'fa-solid fa-wallet', category: 'webtools' },
  { id: 'simple_budget', name: '极简记账', desc: '像计算器一样快速记录每日花销。', href: 'tools/webtools/simple_budget.html', icon: 'fa-solid fa-banknote', category: 'webtools' },
  { id: 'invoice_generator', name: '发票生成器', desc: '快速生成专业 PDF 发票与收据。', href: 'tools/webtools/invoice_generator.html', icon: 'fa-solid fa-file-lines', category: 'webtools' },
  { id: 'expense_splitter', name: 'AA 制计算', desc: '旅行聚餐分账神器，自动计算最优转账方案。', href: 'tools/webtools/expense_splitter.html', icon: 'fa-solid fa-users', category: 'webtools' },
  { id: 'currency_rates', name: '汇率看板', desc: '实时多国货币汇率换算与如展示。', href: 'tools/webtools/currency_rates.html', icon: 'fa-solid fa-globe', category: 'webtools' },
  { id: 'net_worth', name: '资产负债表', desc: '全面盘点个人资产与负债，计算身价。', href: 'tools/webtools/net_worth.html', icon: 'fa-solid fa-landmark', category: 'webtools' },
  { id: 'fire_calculator', name: 'FIRE 计算器', desc: '不仅是计算，更是通往财务自由的路线图。', href: 'tools/webtools/fire_calculator.html', icon: 'fa-solid fa-flame', category: 'webtools' },
  { id: 'savings_goal', name: '存钱目标', desc: '设定买车/旅行目标，可视化存钱进度。', href: 'tools/webtools/savings_goal.html', icon: 'fa-solid fa-bullseye', category: 'webtools' },
  
  // ================== 实用工具 (Utilities) ==================
  { id: 'qr_code_studio', name: '二维码美化工作室', desc: '生成带有颜色、Logo 和样式的个性化二维码。', href: 'tools/webtools/qr_code_studio.html', icon: 'fa-solid fa-qr-code', category: 'webtools' },
  { id: 'password_manager', name: '私密密码本', desc: '本地加密存储与强密码生成，安全管理账号信息。', href: 'tools/webtools/password_manager.html', icon: 'fa-solid fa-key', category: 'webtools' },
  { id: 'diet_diary', name: '饮食日记', desc: '记录每日饮食与热量摄入，集成喝水记录。', href: 'tools/webtools/diet_diary.html', icon: 'fa-solid fa-utensils', category: 'webtools' },
  { id: 'meal_planner', name: '营养餐计划', desc: '规划一周餐饮，支持自动生成采购清单。', href: 'tools/webtools/meal_planner.html', icon: 'fa-solid fa-calendar', category: 'webtools' },
  { id: 'medication_tracker', name: '用药提醒', desc: '添加药品与服用时间，每日打卡确保准时用药。', href: 'tools/webtools/medication_tracker.html', icon: 'fa-solid fa-pill', category: 'webtools' },
  { id: 'decision_maker', name: '选择纠结终端', desc: '转盘或随机抽取，帮你快速做出日常小决定。', href: 'tools/webtools/decision_maker.html', icon: 'fa-solid fa-shuffle', category: 'webtools' },
  { id: 'travel_packing', name: '旅行清单', desc: '旅行打包助手，内置多种场景清单模板。', href: 'tools/webtools/travel_packing.html', icon: 'fa-solid fa-plane', category: 'webtools' },
  { id: 'gift_tracker', name: '礼物清单', desc: '管理送礼对象、创意与预算，记录送礼状态。', href: 'tools/webtools/gift_tracker.html', icon: 'fa-solid fa-gift', category: 'webtools' },
  { id: 'party_planner', name: '聚会策划', desc: '策划聚会活动，管理宾客名单与待办事项。', href: 'tools/webtools/party_planner.html', icon: 'fa-solid fa-party-popper', category: 'webtools' },
  { id: 'white_noise', name: '白噪音空间', desc: '雨声、篝火、咖啡馆... 营造专注或助眠的听觉环境。', href: 'tools/webtools/white_noise.html', icon: 'fa-solid fa-headphones', category: 'webtools' },
  { id: 'life_progress', name: '人生进度条', desc: '可视化展示今年、甚至人生的进度，提供时间紧迫感。', href: 'tools/webtools/life_progress.html', icon: 'fa-solid fa-hourglass', category: 'webtools' },
  { id: 'shopping_list', name: '智能购物清单', desc: '带有预算估算的分类购物清单。', href: 'tools/webtools/shopping_list.html', icon: 'fa-solid fa-shopping-cart', category: 'webtools' },
  { id: 'budget_planner', name: '预算分配器', desc: '基于 50/30/20 法则的收入分配工具。', href: 'tools/webtools/budget_planner.html', icon: 'fa-solid fa-pie-chart', category: 'webtools' },
  { id: 'unit_converter', name: '单位转换大师', desc: '常用物理量（长度、重量、温度等）快速换算。', href: 'tools/webtools/unit_converter.html', icon: 'fa-solid fa-arrow-right-left', category: 'webtools' },
  { id: 'random_generator', name: '全能随机生成器', desc: '生成随机数、字符串、颜色、UUID 等。', href: 'tools/webtools/random_generator.html', icon: 'fa-solid fa-dices', category: 'webtools' },
  { id: 'stopwatch', name: '多功能秒表', desc: '支持正计时、倒计时与分段计次。', href: 'tools/webtools/stopwatch.html', icon: 'fa-solid fa-timer', category: 'webtools' },
  { id: 'wishlist', name: '愿望清单', desc: '管理想买的物品，追踪价格与预算。', href: 'tools/webtools/wishlist.html', icon: 'fa-solid fa-gift', category: 'webtools' },

  // ================== 学习与创作 (Learning & Creation) ==================
  { id: 'reading_list', name: '阅读书单管理', desc: '记录想读的书籍与阅读进度，生成阅读报告。', href: 'tools/webtools/reading_list.html', icon: 'fa-solid fa-book', category: 'webtools' },
  { id: 'flashcards', name: '知识闪卡制作', desc: '制作翻转记忆卡片，辅助背单词或知识点。', href: 'tools/webtools/flashcards.html', icon: 'fa-solid fa-layers', category: 'webtools' },
  { id: 'resume_builder', name: '极简简历生成器', desc: '模块化填写信息，一键导出用于求职的 PDF 简历。', href: 'tools/webtools/resume_builder.html', icon: 'fa-solid fa-file-lines', category: 'webtools' },
  { id: 'color_palette', name: '配色灵感库', desc: '随机生成色彩搭配方案，服务于设计与穿搭。', href: 'tools/webtools/color_palette.html', icon: 'fa-solid fa-palette', category: 'webtools' },
  { id: 'movie_tracker', name: '影视追踪', desc: '记录想看、在看、已看的影视作品与评分。', href: 'tools/webtools/movie_tracker.html', icon: 'fa-solid fa-film', category: 'webtools' },
  { id: 'vocabulary', name: '背单词', desc: '基于艾宾浩斯曲线的单词记忆卡片。', href: 'tools/webtools/vocabulary.html', icon: 'fa-solid fa-brain-circuit', category: 'webtools' },
  
  // ================== 开发者工具 (Developer Tools) ==================
  { id: 'json_formatter', name: 'JSON 格式化', desc: '美化、压缩与校验 JSON 数据。', href: 'tools/webtools/json_formatter.html', icon: 'fa-solid fa-code', category: 'webtools' },
  { id: 'base64_converter', name: 'Base64 转换', desc: '文本与文件的 Base64 编码与解码工具。', href: 'tools/webtools/base64_converter.html', icon: 'fa-solid fa-file-code', category: 'webtools' },
  { id: 'regex_tester', name: '正则测试器', desc: '实时测试正则表达式匹配情况。', href: 'tools/webtools/regex_tester.html', icon: 'fa-solid fa-regex', category: 'webtools' },
  { id: 'markdown_preview', name: 'Markdown 预览', desc: 'Markdown 实时编辑与预览工具。', href: 'tools/webtools/markdown_preview.html', icon: 'fa-solid fa-file-lines', category: 'webtools' },
  { id: 'image_compressor', name: '图片压缩', desc: '浏览器端离线压缩图片，保护隐私且高效。', href: 'tools/webtools/image_compressor.html', icon: 'fa-solid fa-image', category: 'webtools' },
  { id: 'color_converter', name: '颜色转换器', desc: 'RGB、HEX、HSL 颜色格式互相转换。', href: 'tools/webtools/color_converter.html', icon: 'fa-solid fa-palette', category: 'webtools' },
  { id: 'timestamp_converter', name: '时间戳转换', desc: 'Unix 时间戳与日期时间的相互转换。', href: 'tools/webtools/timestamp_converter.html', icon: 'fa-solid fa-clock', category: 'webtools' },
  { id: 'sql_generator', name: 'SQL 生成器', desc: '可视化生成 Create Table 建表语句。', href: 'tools/webtools/sql_generator.html', icon: 'fa-solid fa-database', category: 'webtools' },
  { id: 'cron_generator', name: 'Cron 生成器', desc: '图形化生成 Cron 定时任务表达式。', href: 'tools/webtools/cron_generator.html',         icon: 'fa-solid fa-clock', category: 'webtools' },
  { id: 'uuid_generator', name: 'UUID 生成器', desc: '批量生成 UUID/GUID，支持多种格式配置。', href: 'tools/webtools/uuid_generator.html', icon: 'fa-solid fa-fingerprint', category: 'webtools' },
  { id: 'hash_calculator', name: '哈希计算器', desc: '计算文本的 MD5、SHA-1、SHA-256 哈希值。', href: 'tools/webtools/hash_calculator.html', icon: 'fa-solid fa-hash', category: 'webtools' },
  { id: 'text_diff', name: '文本对比', desc: '高亮显示两段文本的差异 (Diff)。', href: 'tools/webtools/text_diff.html', icon: 'fa-solid fa-git-compare-arrows', category: 'webtools' },
  { id: 'word_counter', name: '字数统计', desc: '统计字符、单词、段落及阅读时间。', href: 'tools/webtools/word_counter.html', icon: 'fa-solid fa-text-cursor-input', category: 'webtools' },
  { id: 'url_encoder', name: 'URL 编码/解码', desc: 'URL Encode/Decode 工具。', href: 'tools/webtools/url_encoder.html', icon: 'fa-solid fa-link', category: 'webtools' },
  { id: 'qr_generator', name: '二维码生成器', desc: '个性化二维码生成与下载。', href: 'tools/webtools/qr_generator.html', icon: 'fa-solid fa-qr-code', category: 'webtools' },
  { id: 'password_generator', name: '强密码生成', desc: '自定义规则生成高强度随机密码。', href: 'tools/webtools/password_generator.html', icon: 'fa-solid fa-shield-check', category: 'webtools' },
  { id: 'html_entities', name: 'HTML 实体转换', desc: 'HTML 实体编码与解码速查。', href: 'tools/webtools/html_entities.html', icon: 'fa-solid fa-code', category: 'webtools' },
  { id: 'css_gradient', name: 'CSS 渐变生成', desc: '可视化生成线性与径向渐变 CSS。', href: 'tools/webtools/css_gradient.html', icon: 'fa-solid fa-palette', category: 'webtools' },
  { id: 'meta_tag_generator', name: 'Meta 标签生成', desc: 'SEO Meta 标签与 Open Graph 社交卡片生成。', href: 'tools/webtools/meta_tag_generator.html', icon: 'fa-solid fa-tag', category: 'webtools' },
  { id: 'flexbox_playground', name: 'Flexbox 演练', desc: '可视化调整 Flex 容器与子元素属性。', href: 'tools/webtools/flexbox_playground.html', icon: 'fa-solid fa-layout', category: 'webtools' },
  { id: 'grid_playground', name: 'Grid 布局演练', desc: '可视化 CSS Grid 网格布局生成与调试。', href: 'tools/webtools/grid_playground.html', icon: 'fa-solid fa-table-cells', category: 'webtools' },
  
  { id: 'image_cropper', name: '图片裁剪', desc: '基于 Cropper.js 的图片裁剪工具。', href: 'tools/webtools/image_cropper.html', icon: 'fa-solid fa-scissors', category: 'webtools' },
  { id: 'image_color_picker', name: '图片取色与调色', desc: '提取图片主色调或吸管取色。', href: 'tools/webtools/image_color_picker.html', icon: 'fa-solid fa-pipette', category: 'webtools' },
  { id: 'image_filters', name: '图片滤镜', desc: 'CSS/Canvas 滤镜调节与预览。', href: 'tools/webtools/image_filters.html', icon: 'fa-solid fa-wand-magic-sparkles', category: 'webtools' },
  { id: 'exif_viewer', name: 'Exif 查看器', desc: '查看照片的 Exif 元数据信息。', href: 'tools/webtools/exif_viewer.html', icon: 'fa-solid fa-camera', category: 'webtools' },
  { id: 'svg_editor', name: 'SVG 编辑器', desc: '简单的 SVG 代码预览与调整。', href: 'tools/webtools/svg_editor.html', icon: 'fa-solid fa-pen-nib', category: 'webtools' },
  { id: 'image_to_ascii', name: '图片转字符画', desc: '生成 ASCII 字符风格的图片艺术。', href: 'tools/webtools/image_to_ascii.html', icon: 'fa-solid fa-binary', category: 'webtools' },
  { id: 'anniversary_maker', name: '纪念日海报', desc: '生成精美纪念日倒数日海报。', href: 'tools/webtools/anniversary_maker.html', icon: 'fa-solid fa-calendar-heart', category: 'webtools' },
  { id: 'csv_json_converter', name: 'CSV/JSON 转换', desc: 'CSV 与 JSON 数据格式互转。', href: 'tools/webtools/csv_json_converter.html',         icon: 'fa-solid fa-file-code', category: 'webtools' },
  { id: 'text_case_converter', name: '文本大小写', desc: '各种命名风格与大小写转换。', href: 'tools/webtools/text_case_converter.html', icon: 'fa-solid fa-case-sensitive', category: 'webtools' },
  { id: 'typing_test', name: '打字练习', desc: '极简打字速度测试与练习。', href: 'tools/webtools/typing_test.html', icon: 'fa-solid fa-keyboard', category: 'webtools' },
  
  // ================== 进阶学习 (Advanced Learning) ==================
  { id: 'sql_playground', name: 'SQL 交互实验室', desc: '纯前端模拟 SQL 数据库环境，练习增删改查操作。', href: 'tools/Advanced/sql_database_demo.html', icon: 'fa-solid fa-database', category: 'advanced_learning' },
  { id: 'local_file_editor', name: '本地文件编辑器', desc: '基于 File System Access API，直接读写本地文件。', href: 'tools/Advanced/file_system_editor.html',         icon: 'fa-solid fa-pen-to-square', category: 'advanced_learning' },
  { id: 'hardware_dashboard', name: '硬件传感器面板', desc: '读取电池、网络、陀螺仪、震动等设备传感器数据。', href: 'tools/Advanced/hardware_dashboard.html',         icon: 'fa-solid fa-fingerprint', category: 'advanced_learning' },
];
