window.toolCollections = window.toolCollections || {};
window.toolCollections.life_planning = [
    {
        id: 'travel_planner',
        name: '旅行规划师',
        desc: '目的地/天数/预算/偏好→大致行程→用户调整→每天详细安排（交通/住宿/餐饮/景点）→导出行程单。',
        href: 'tools/life_planning/travel_planner.html',
        icon: 'fa-solid fa-plane-departure',
        category: 'life_planning',
        tags: ['小红书'],
        isNew: true,
        complexity: 3,
        iconBg: 'bg-teal-50',
        iconColor: 'text-teal-600',
        borderColor: 'teal-200',
        hoverTextColor: 'text-teal-600',
        linkColor: 'text-teal-600'
    },
    {
        id: 'renovation_budget',
        name: '装修预算规划',
        desc: '户型/面积/风格/预算→分项预算→细化材料清单+人工费+时间表→导出预算表。',
        href: 'tools/life_planning/renovation_budget.html',
        icon: 'fa-solid fa-house-chimney',
        category: 'life_planning',
        tags: ['小红书'],
        isNew: true,
        complexity: 3,
        iconBg: 'bg-orange-50',
        iconColor: 'text-orange-600',
        borderColor: 'orange-200',
        hoverTextColor: 'text-orange-600',
        linkColor: 'text-orange-600'
    },
    {
        id: 'recipe_builder',
        name: '食谱搭配师',
        desc: '已有食材/口味/人数/忌口→推荐菜品→详细步骤+营养分析+采购清单，解决"今天吃什么"。',
        href: 'tools/life_planning/recipe_builder.html',
        icon: 'fa-solid fa-utensils',
        category: 'life_planning',
        tags: ['小红书', '抖音'],
        isNew: true,
        complexity: 2,
        iconBg: 'bg-rose-50',
        iconColor: 'text-rose-600',
        borderColor: 'rose-200',
        hoverTextColor: 'text-rose-600',
        linkColor: 'text-rose-600'
    },
    {
        id: 'health_report_reader',
        name: '健康报告解读器',
        desc: '粘贴体检数据→逐项解读指标→标记异常项→给出生活建议+复查建议→导出健康报告。',
        href: 'tools/life_planning/health_report_reader.html',
        icon: 'fa-solid fa-heart-pulse',
        category: 'life_planning',
        tags: [],
        isNew: true,
        complexity: 3,
        iconBg: 'bg-red-50',
        iconColor: 'text-red-600',
        borderColor: 'red-200',
        hoverTextColor: 'text-red-600',
        linkColor: 'text-red-600'
    },
    {
        id: 'decision_matrix',
        name: '多方案决策矩阵',
        desc: '候选方案→多维度评分（自定义权重）→加权对比矩阵→可视化评分→最终建议，理性决策。',
        href: 'tools/life_planning/decision_matrix.html',
        icon: 'fa-solid fa-scale-balanced',
        category: 'life_planning',
        tags: ['职场'],
        isNew: true,
        complexity: 3,
        iconBg: 'bg-indigo-50',
        iconColor: 'text-indigo-600',
        borderColor: 'indigo-200',
        hoverTextColor: 'text-indigo-600',
        linkColor: 'text-indigo-600'
    }
];
