window.toolCollections = window.toolCollections || {};
window.toolCollections.study = [
    {
        id: 'study_planner',
        name: '智能学习计划生成器',
        desc: '基于你的目标和可用时间，生成定制化的学习计划表。支持导出 Excel 或 Notion 格式。',
        href: 'tools/study/study_planner.html',
        icon: 'fa-solid fa-calendar-check',
        category: 'study',
        tags: ['计划', '效率'],
        isNew: true,
        iconBg: 'bg-indigo-50',
        iconColor: 'text-indigo-600',
        borderColor: 'indigo-200',
        hoverTextColor: 'text-indigo-600',
        linkColor: 'text-indigo-600'
    },
    {
        id: 'flashcards',
        name: '智能记忆卡片',
        desc: '基于艾宾浩斯遗忘曲线的复习工具。支持 Markdown 和图片，AI 辅助生成卡片内容。',
        href: 'tools/study/flashcards.html',
        icon: 'fa-solid fa-clipboard-list',
        category: 'study',
        tags: ['记忆', '复习'],
        isNew: true,
        iconBg: 'bg-green-50',
        iconColor: 'text-green-600',
        borderColor: 'green-200',
        hoverTextColor: 'text-green-600',
        linkColor: 'text-green-600'
    },
    {
        id: 'speaking_simulator',
        name: '雅思口语模拟器',
        desc: 'AI 考官一对一陪练。模拟真实考试流程，提供实时评分和语法纠错建议。',
        href: 'tools/study/speaking_simulator.html',
        icon: 'fa-solid fa-language',
        category: 'study',
        tags: ['英语', '口语'],
        isNew: true,
        iconBg: 'bg-rose-50',
        iconColor: 'text-rose-600',
        borderColor: 'rose-200',
        hoverTextColor: 'text-rose-600',
        linkColor: 'text-rose-600'
    },
    {
        id: 'vocab_builder',
        name: '场景词汇构建器',
        desc: '告别死记硬背。输入场景描述，AI 生成相关的高频词汇、短语和例句，构建关联记忆一图流。',
        href: 'tools/study/vocab_builder.html',
        icon: 'fa-solid fa-book-open',
        category: 'study',
        tags: ['英语', '词汇'],
        isNew: true,
        iconBg: 'bg-amber-50',
        iconColor: 'text-amber-600',
        borderColor: 'amber-200',
        hoverTextColor: 'text-amber-600',
        linkColor: 'text-amber-600'
    },
    {
        id: 'writing_clinic',
        name: '英文写作诊所',
        desc: '输入你的作文，AI 像外教一样批改。专注于逻辑连贯性、地道表达和高级词汇替换建议。',
        href: 'tools/study/writing_clinic.html',
        icon: 'fa-solid fa-pen-nib',
        category: 'study',
        tags: ['英语', '写作'],
        isNew: true,
        iconBg: 'bg-blue-50',
        iconColor: 'text-blue-600',
        borderColor: 'blue-200',
        hoverTextColor: 'text-blue-600',
        linkColor: 'text-blue-600'
    },
    {
        id: 'listening_shadowing',
        name: '听力跟读训练',
        desc: '精听与跟读一体化工具。AI 语音打分，支持调节语速、循环播放和生词标记。',
        href: 'tools/study/listening_shadowing.html',
        icon: 'fa-solid fa-headphones',
        category: 'study',
        tags: ['英语', '听力'],
        isNew: true,
        iconBg: 'bg-cyan-50',
        iconColor: 'text-cyan-600',
        borderColor: 'cyan-200',
        hoverTextColor: 'text-cyan-600',
        linkColor: 'text-cyan-600'
    },
    {
        id: 'exam_generator',
        name: '智能出题器',
        desc: '输入学习资料或文本，AI 自动生成选择题、填空题和简答题，快速检测学习效果。',
        href: 'tools/study/exam_generator.html',
        icon: 'fa-solid fa-file-question',
        category: 'study',
        tags: ['考试', '测试'],
        isNew: true,
        iconBg: 'bg-purple-50',
        iconColor: 'text-purple-600',
        borderColor: 'purple-200',
        hoverTextColor: 'text-purple-600',
        linkColor: 'text-purple-600'
    },
    {
        id: 'reading_sprint',
        name: '阅读冲刺训练',
        desc: 'RSVP 快速阅读训练工具。提高阅读速度和专注力，适合长文阅读突击。',
        href: 'tools/study/reading_sprint.html',
        icon: 'fa-solid fa-bolt',
        category: 'study',
        tags: ['阅读', '速读'],
        isNew: true,
        iconBg: 'bg-orange-50',
        iconColor: 'text-orange-600',
        borderColor: 'orange-200',
        hoverTextColor: 'text-orange-600',
        linkColor: 'text-orange-600'
    },
    {
        id: 'learning_methods',
        name: '学习方法库',
        desc: '费曼技巧、番茄工作法、康奈尔笔记法... AI 教你如何科学高效地学习任何技能。',
        href: 'tools/study/learning_methods.html',
        icon: 'fa-solid fa-brain',
        category: 'study',
        tags: ['方法论', '自学'],
        isNew: true,
        iconBg: 'bg-teal-50',
        iconColor: 'text-teal-600',
        borderColor: 'teal-200',
        hoverTextColor: 'text-teal-600',
        linkColor: 'text-teal-600'
    }
];
