window.toolCollections = window.toolCollections || {};
window.toolCollections.creative_methods = [
    { id: 'cross_domain_spark', name: '跨界灵感发射器', desc: '随机领域视角输出启发句，让思路“换轨”。', href: 'tools/creative_methods/cross_domain_spark.html',         icon: 'fa-solid fa-paper-plane', category: 'creative_methods', tags: ['灵感', '脑洞'], isNew: true, iconBg: 'bg-violet-50', iconColor: 'text-violet-600', borderColor: 'violet-200', hoverTextColor: 'text-violet-600', linkColor: 'text-violet-600', badgeStyle: 'bg-violet-100 text-violet-700' },
    { id: 'inspiration_wheel', name: '灵感转盘', desc: '创意枯竭？转一下！随机抽取关键词（对象/场景/风格/冲突），强迫联想，打破思维定势。', href: 'tools/creative_methods/inspiration_wheel.html',         icon: 'fa-solid fa-circle-notch', category: 'creative_methods', tags: ['灵感', '创意'], isNew: true, iconBg: 'bg-pink-50', iconColor: 'text-pink-600', borderColor: 'pink-200', hoverTextColor: 'text-pink-600', linkColor: 'text-pink-600', badgeStyle: 'bg-pink-100 text-pink-700' },
    { id: 'brainstorm_map', name: '头脑风暴 · 思维导图', desc: '从主题出发生成多层发散路径，适合启动新项目或挖掘突破口。', href: 'tools/creative_methods/brainstorm_map.html',         icon: 'fa-solid fa-sitemap', category: 'creative_methods', tags: ['创意', '思维导图'], isNew: true, iconBg: 'bg-indigo-50', iconColor: 'text-indigo-600', borderColor: 'indigo-200', hoverTextColor: 'text-indigo-600', linkColor: 'text-indigo-600' },
    { id: 'nine_grid', name: '九宫格创意', desc: '将主题拆成 3×3 结构，快速获得九个视角与对应行动点。', href: 'tools/creative_methods/nine_grid.html',         icon: 'fa-solid fa-table-cells', category: 'creative_methods', tags: ['创意', '发散'], isNew: true, iconBg: 'bg-blue-50', iconColor: 'text-blue-600', borderColor: 'blue-200', hoverTextColor: 'text-blue-600', linkColor: 'text-blue-600' },
    { id: 'six_hats', name: '六顶思考帽', desc: '用不同角色切换视角，涵盖事实、情感、风险与创意方案。', href: 'tools/creative_methods/six_hats.html', icon: 'fa-solid fa-graduation-cap', category: 'creative_methods', tags: ['思考', '决策'], isNew: true, iconBg: 'bg-yellow-50', iconColor: 'text-yellow-600', borderColor: 'yellow-200', hoverTextColor: 'text-yellow-600', linkColor: 'text-yellow-600' },
    { id: 'scamper', name: 'SCAMPER 创意改造', desc: '替换、组合、调整、放大、缩小、用途转移等七步改造。', href: 'tools/creative_methods/scamper.html', icon: 'fa-solid fa-shuffle', category: 'creative_methods', tags: ['创意', '改造'], isNew: true, iconBg: 'bg-purple-50', iconColor: 'text-purple-600', borderColor: 'purple-200', hoverTextColor: 'text-purple-600', linkColor: 'text-purple-600' },
    { id: 'problem_canvas', name: '问题解决画布 (5W1H)', desc: '用结构化提问澄清问题边界，输出清晰可执行的解决路径。', href: 'tools/creative_methods/problem_canvas.html',         icon: 'fa-solid fa-bullseye', category: 'creative_methods', tags: ['问题解决', '思维'], isNew: true, iconBg: 'bg-red-50', iconColor: 'text-red-600', borderColor: 'red-200', hoverTextColor: 'text-red-600', linkColor: 'text-red-600' },
];
