window.toolCollections = window.toolCollections || {};
window.toolCollections.visual_creative = [
    {
        id: 'greeting_card',
        name: 'HTML 贺卡工坊',
        desc: '描述场景与祝福语，AI 流式生成可独立打开的 HTML/CSS 贺卡（内联样式与动画），支持预览、复制与下载。',
        href: 'tools/visual_creative/greeting_card.html',
        icon: 'fa-solid fa-envelope-open-text',
        category: 'visual_creative',
        tags: ['小红书', '公众号'],
        isNew: true,
        complexity: 2,
        iconBg: 'bg-pink-50',
        iconColor: 'text-pink-600',
        borderColor: 'pink-200',
        hoverTextColor: 'text-pink-600',
        linkColor: 'text-pink-600'
    },
    {
        id: 'color_palette',
        name: 'AI 配色大师',
        desc: '描述一个场景、情绪或风格，AI 生成专业配色方案并实时渲染色卡预览，设计师必备。',
        href: 'tools/visual_creative/color_palette.html',
        icon: 'fa-solid fa-palette',
        category: 'visual_creative',
        tags: ['小红书'],
        isNew: true,
        complexity: 2,
        iconBg: 'bg-fuchsia-50',
        iconColor: 'text-fuchsia-600',
        borderColor: 'fuchsia-200',
        hoverTextColor: 'text-fuchsia-600',
        linkColor: 'text-fuchsia-600'
    },
    {
        id: 'svg_illustrator',
        name: 'SVG 插画生成器',
        desc: '描述你想要的插画，AI 直接写出 SVG 代码并实时渲染。矢量图，无限放大不失真。',
        href: 'tools/visual_creative/svg_illustrator.html',
        icon: 'fa-solid fa-bezier-curve',
        category: 'visual_creative',
        tags: [],
        isNew: true,
        complexity: 3,
        iconBg: 'bg-indigo-50',
        iconColor: 'text-indigo-600',
        borderColor: 'indigo-200',
        hoverTextColor: 'text-indigo-600',
        linkColor: 'text-indigo-600'
    },
    {
        id: 'css_animation',
        name: 'CSS 动效工坊',
        desc: '用自然语言描述你想要的动画效果，AI 生成 CSS 动画代码并实时预览，学习和灵感利器。',
        href: 'tools/visual_creative/css_animation.html',
        icon: 'fa-solid fa-film',
        category: 'visual_creative',
        tags: [],
        isNew: true,
        complexity: 3,
        iconBg: 'bg-cyan-50',
        iconColor: 'text-cyan-600',
        borderColor: 'cyan-200',
        hoverTextColor: 'text-cyan-600',
        linkColor: 'text-cyan-600'
    },
    {
        id: 'life_dashboard',
        name: '人生仪表盘',
        desc: '输入你的人生数据（年龄、爱好、成就、目标），AI 生成一个炫酷的可视化人生仪表盘页面。',
        href: 'tools/visual_creative/life_dashboard.html',
        icon: 'fa-solid fa-gauge-high',
        category: 'visual_creative',
        tags: ['小红书'],
        isNew: true,
        complexity: 3,
        iconBg: 'bg-violet-50',
        iconColor: 'text-violet-600',
        borderColor: 'violet-200',
        hoverTextColor: 'text-violet-600',
        linkColor: 'text-violet-600'
    }
];
