window.toolCollections = window.toolCollections || {};
window.toolCollections.writing = [
    { id: 'chat_writer', name: '对话式写作助手', desc: '像 ChatGPT 一样多轮对话，逐步打磨文章。支持构思大纲、扩写润色、风格调整，对话历史自动保存。', href: 'tools/writing/chat_writer.html', icon: 'fa-solid fa-comment-dots', category: 'writing', tags: ['公众号', '知乎', '小红书'], isNew: true, iconBg: 'bg-blue-50', iconColor: 'text-blue-600', borderColor: 'blue-200', hoverTextColor: 'text-blue-600', linkColor: 'text-blue-600' },
    { id: 'deep_writer', name: 'DeepWriter 写作专家', desc: '全能型长文写作工具。支持大纲生成、分段扩写、润色优化。适合公众号文章、报告等深度内容。', href: 'tools/writing/deep_writer.html', icon: 'fa-solid fa-pen-nib', category: 'writing', tags: ['公众号', '知乎'], isNew: false, iconBg: 'bg-indigo-50', iconColor: 'text-indigo-600', borderColor: 'indigo-200', hoverTextColor: 'text-indigo-600', linkColor: 'text-indigo-600' },
    { id: 'multi_article_generator', name: 'AI 批量内容生成器', desc: '基于表格的批量内容生产工具。支持自定义输入列、JSON 结构化输出及多行并行生成。', href: 'tools/writing/multi_article_generator.html', icon: 'fa-solid fa-table-list', category: 'writing', tags: ['小红书', '公众号', '电商'], isNew: true, iconBg: 'bg-pink-50', iconColor: 'text-pink-600', borderColor: 'pink-200', hoverTextColor: 'text-pink-600', linkColor: 'text-pink-600', badgeStyle: 'bg-pink-100 text-pink-700' },
    { id: 'zhihu_answer', name: '知乎专业回答生成器', desc: '生成知乎风格专业回答。干货型、故事型、观点型、科普型四种风格，支持字数控制和 V4 Pro 深度思考。', href: 'tools/writing/zhihu_answer.html', icon: 'fa-solid fa-graduation-cap', category: 'writing', tags: ['知乎'], isNew: true, iconBg: 'bg-blue-50', iconColor: 'text-blue-600', borderColor: 'blue-200', hoverTextColor: 'text-blue-600', linkColor: 'text-blue-600' },
    { id: 'fanfic_dialogue_generator', name: '同人小说生成器', desc: '对话体同人小说创作助手。设置角色性格和情节，AI 自动生成对话体小说，支持续写和导出。', href: 'tools/writing/fanfic_dialogue_generator.html', icon: 'fa-solid fa-feather', category: 'writing', tags: ['小说', '创意写作'], isNew: true, iconBg: 'bg-purple-50', iconColor: 'text-purple-600', borderColor: 'purple-200', hoverTextColor: 'text-purple-600', linkColor: 'text-purple-600', badgeStyle: 'bg-purple-100 text-purple-700' },
    { id: 'business_email_writer', name: '商务邮件写作助手', desc: '职场刚需工具。12种邮件类型模板，支持多种收件人身份和语气风格，一键生成专业商务邮件。', href: 'tools/writing/business_email_writer.html', icon: 'fa-solid fa-envelope', category: 'writing', tags: ['职场', '邮件'], isNew: true, iconBg: 'bg-indigo-50', iconColor: 'text-indigo-600', borderColor: 'indigo-200', hoverTextColor: 'text-indigo-600', linkColor: 'text-indigo-600' },
    { id: 'love_letter_generator', name: '情书/表白文案生成器', desc: '浪漫、文艺、真诚等多风格的情感表达。精美信纸渲染，支持6种艺术字体，让每一封情书都充满心意。', href: 'tools/writing/love_letter_generator.html', icon: 'fa-solid fa-heart', category: 'writing', tags: ['情感表达', '私域'], isNew: true, iconBg: 'bg-rose-50', iconColor: 'text-rose-600', borderColor: 'rose-200', hoverTextColor: 'text-rose-600', linkColor: 'text-rose-600' },
];
