window.toolCollections = window.toolCollections || {};
window.toolCollections.html_beginner = [
    // 🌱 HTML 入门系列 - 纯新手从零开始
    { id: 'html_lesson_01', name: 'HTML 入门第一课', desc: '从空白页到可运行工具。理解 HTML 本质，掌握基础标签，编写你的第一个网页。', href: 'tools/ai_basics/html-basics/01-html-first-lesson.html', icon: 'fa-solid fa-code', category: 'html_beginner', tags: ['HTML入门', '教程', '新手'], isNew: true, iconBg: 'bg-green-50', iconColor: 'text-green-600', borderColor: 'green-200', hoverTextColor: 'text-green-600', linkColor: 'text-green-600', badgeStyle: 'bg-green-100 text-green-700' },
    { id: 'html_lesson_02', name: '开发环境搭建', desc: '你的开发环境搭建指南。安装 VS Code、浏览器开发者工具、必备插件，配置完整的开发工作流。', href: 'tools/ai_basics/html-basics/02-dev-environment.html', icon: 'fa-solid fa-tools', category: 'html_beginner', tags: ['环境配置', '教程', '新手'], isNew: true, iconBg: 'bg-green-50', iconColor: 'text-green-600', borderColor: 'green-200', hoverTextColor: 'text-green-600', linkColor: 'text-green-600', badgeStyle: 'bg-green-100 text-green-700' },
    { id: 'html_lesson_03', name: 'Prompt 驱动开发', desc: '从想法到代码。用自然语言描述需求，AI 帮你生成代码，无需精通编程也能快速实现想法。', href: 'tools/ai_basics/html-basics/03-prompt-driven-dev.html', icon: 'fa-solid fa-robot', category: 'html_beginner', tags: ['Prompt', '教程', 'AI开发'], isNew: true, iconBg: 'bg-green-50', iconColor: 'text-green-600', borderColor: 'green-200', hoverTextColor: 'text-green-600', linkColor: 'text-green-600', badgeStyle: 'bg-green-100 text-green-700' },
    { id: 'html_lesson_04', name: '调试指南', desc: '常见错误排查手册。学会使用控制台、解读错误信息、修复常见问题，成为调试高手。', href: 'tools/ai_basics/html-basics/04-debugging-guide.html', icon: 'fa-solid fa-bug', category: 'html_beginner', tags: ['调试', '教程', '问题解决'], isNew: true, iconBg: 'bg-green-50', iconColor: 'text-green-600', borderColor: 'green-200', hoverTextColor: 'text-green-600', linkColor: 'text-green-600', badgeStyle: 'bg-green-100 text-green-700' },
    { id: 'html_lesson_05', name: '项目结构', desc: '理解现有工具的组成。分析 HTML、JavaScript、CSS 的组织方式，为修改和创造打下基础。', href: 'tools/ai_basics/html-basics/05-project-structure.html', icon: 'fa-solid fa-folder-tree', category: 'html_beginner', tags: ['项目结构', '教程', '进阶'], isNew: true, iconBg: 'bg-green-50', iconColor: 'text-green-600', borderColor: 'green-200', hoverTextColor: 'text-green-600', linkColor: 'text-green-600', badgeStyle: 'bg-green-100 text-green-700' },
    { id: 'html_lesson_06', name: 'CSS 基础样式', desc: '让工具更好看。掌握 Flexbox 布局、间距控制、颜色系统，让你的工具不仅能用还能好看。', href: 'tools/ai_basics/html-basics/06-css-basics.html', icon: 'fa-solid fa-palette', category: 'html_beginner', tags: ['CSS', '教程', '样式'], isNew: true, iconBg: 'bg-green-50', iconColor: 'text-green-600', borderColor: 'green-200', hoverTextColor: 'text-green-600', linkColor: 'text-green-600', badgeStyle: 'bg-green-100 text-green-700' },
    { id: 'html_lesson_07', name: '部署与分享', desc: '让你的工具被更多人使用。GitHub Pages、Vercel 部署教程，以及多种分享方式的完整指南。', href: 'tools/ai_basics/html-basics/07-deployment.html', icon: 'fa-solid fa-share-alt', category: 'html_beginner', tags: ['部署', '教程', '分享'], isNew: true, iconBg: 'bg-green-50', iconColor: 'text-green-600', borderColor: 'green-200', hoverTextColor: 'text-green-600', linkColor: 'text-green-600', badgeStyle: 'bg-green-100 text-green-700' },
    { id: 'html_lesson_08', name: '进阶之路', desc: '从工具到产品的升级路线图。回顾学习成果，探索进阶方向，规划你的开发者成长之路。', href: 'tools/ai_basics/html-basics/08-next-steps.html', icon: 'fa-solid fa-rocket', category: 'html_beginner', tags: ['进阶', '教程', '总结'], isNew: true, iconBg: 'bg-green-50', iconColor: 'text-green-600', borderColor: 'green-200', hoverTextColor: 'text-green-600', linkColor: 'text-green-600', badgeStyle: 'bg-green-100 text-green-700' },
];

window.toolCollections.ai_dev_tools = [
    // 🌿 AI 开发工具集 - 实战工具和应用
    { id: 'html_tool_builder', name: 'AI 全栈工具脚手架', desc: 'Vibe Coding 启动器。一句话描述需求，AI 自动生成包含 Vue3 + Tailwind + DeepSeek 完整配置的单文件 HTML 工具。', href: 'tools/ai_basics/html_tool_builder.html', icon: 'fa-solid fa-hammer', category: 'ai_dev_tools', tags: ['代码生成', '脚手架'], isNew: true, iconBg: 'bg-blue-50', iconColor: 'text-blue-600', borderColor: 'blue-200', hoverTextColor: 'text-blue-600', linkColor: 'text-blue-600', badgeStyle: 'bg-blue-100 text-blue-700' },
    { id: 'api_intro', name: 'API 请求代码详解', desc: 'AI 基础知识教程。详细讲解如何通过代码调用 AI API，理解请求结构、参数配置和响应处理。', href: 'tools/ai_basics/api_intro.html', icon: 'fa-solid fa-code', category: 'ai_dev_tools', tags: ['AI学习', '开发指南'], isNew: true, iconBg: 'bg-blue-50', iconColor: 'text-blue-600', borderColor: 'blue-200', hoverTextColor: 'text-blue-600', linkColor: 'text-blue-600', badgeStyle: 'bg-blue-100 text-blue-700' },
    { id: 'llm_api_demo', name: 'LLM API 教学', desc: '一步步学会调用大语言模型 API。从概念到实战，包含简化版 API 封装源码和可交互测试。', href: 'tools/ai_basics/llm-api-demo.html', icon: 'fa-solid fa-graduation-cap', category: 'ai_dev_tools', tags: ['AI学习', 'API', '教程'], isNew: true, iconBg: 'bg-blue-50', iconColor: 'text-blue-600', borderColor: 'blue-200', hoverTextColor: 'text-blue-600', linkColor: 'text-blue-600', badgeStyle: 'bg-blue-100 text-blue-700' },
    { id: 'simple_llm_api_doc', name: 'Simple LLM API 文档', desc: 'simple-llm-api.js 的详细 API 文档，包含类方法、函数参数和使用示例。', href: 'tools/ai_basics/simple-llm-api-doc.html', icon: 'fa-solid fa-book-open', category: 'ai_dev_tools', tags: ['AI学习', 'API', '文档'], isNew: true, iconBg: 'bg-blue-50', iconColor: 'text-blue-600', borderColor: 'blue-200', hoverTextColor: 'text-blue-600', linkColor: 'text-blue-600', badgeStyle: 'bg-blue-100 text-blue-700' },
    { id: 'streaming_demo', name: 'LLM 流式输出演示', desc: '深入理解流式输出原理，包含技术实现、代码示例和可交互的实时演示。', href: 'tools/ai_basics/streaming-demo.html', icon: 'fa-solid fa-wave-square', category: 'ai_dev_tools', tags: ['AI学习', '流式输出', '进阶'], isNew: true, iconBg: 'bg-purple-50', iconColor: 'text-purple-600', borderColor: 'purple-200', hoverTextColor: 'text-purple-600', linkColor: 'text-purple-600', badgeStyle: 'bg-purple-100 text-purple-700' },
    { id: 'api_error_guide', name: 'API 错误代码指南', desc: '报错了怎么办？通俗易懂地解释 4xx/5xx 等常见错误代码，提供小白也能看懂的调试建议。', href: 'tools/ai_basics/api_error_guide.html', icon: 'fa-solid fa-triangle-exclamation', category: 'ai_dev_tools', tags: ['AI学习', '调试'], isNew: true, iconBg: 'bg-blue-50', iconColor: 'text-blue-600', borderColor: 'blue-200', hoverTextColor: 'text-blue-600', linkColor: 'text-blue-600', badgeStyle: 'bg-blue-100 text-blue-700' },
    { id: 'json_intro', name: 'JSON 入门指南', desc: 'AI 基础知识教程。零基础学习 JSON 数据格式，理解 AI 接口的请求和响应结构。', href: 'tools/ai_basics/json_intro.html', icon: 'fa-solid fa-code', category: 'ai_dev_tools', tags: ['AI学习', '开发指南'], isNew: true, iconBg: 'bg-blue-50', iconColor: 'text-blue-600', borderColor: 'blue-200', hoverTextColor: 'text-blue-600', linkColor: 'text-blue-600', badgeStyle: 'bg-blue-100 text-blue-700' },
    { id: 'project_guide', name: '全景指南 & Vibe Coding', desc: '本项目的使用说明书。教你如何利用现有代码结构，通过 Vibe Coding 模式快速复刻和创造新工具。', href: 'tools/ai_basics/guide.html', icon: 'fa-solid fa-book', category: 'ai_dev_tools', tags: ['说明书', '开发指南'], isNew: true, iconBg: 'bg-blue-50', iconColor: 'text-blue-600', borderColor: 'blue-200', hoverTextColor: 'text-blue-600', linkColor: 'text-blue-600', badgeStyle: 'bg-blue-100 text-blue-700' },
    { id: 'personal_website_guide', name: '个人AI网站实战指南', desc: '从简单页面到强大AI门户——打造属于你的AI工具平台', href: 'tools/ai_basics/构建个人AI网站实战.html', icon: 'fa-solid fa-globe', category: 'ai_dev_tools', tags: ['教程', '实战'], isNew: true, iconBg: 'bg-blue-50', iconColor: 'text-blue-600', borderColor: 'blue-200', hoverTextColor: 'text-blue-600', linkColor: 'text-blue-600', badgeStyle: 'bg-blue-100 text-blue-700' },
];

window.toolCollections.advanced_learning = [
    // 💻 开发者工具库 - 前端技术学习与实战
    { id: 'learn_hub', name: 'AI 学习中心', desc: '系统化的 AI 开发课程。包含基础概念、提示工程、工作流及实战指南，适合从零开始的学习者。', href: 'tools/ai_basics/learn_hub.html', icon: 'fa-solid fa-graduation-cap', category: 'advanced_learning', tags: ['教程', '课程'], isNew: true, iconBg: 'bg-slate-50', iconColor: 'text-slate-600', borderColor: 'slate-200', hoverTextColor: 'text-slate-600', linkColor: 'text-slate-600', badgeStyle: 'bg-slate-100 text-slate-700' },
    { id: 'llm_playground', name: 'LLM 交互原理实验室', desc: '12 个交互式实验，深入理解大模型：流式输出、温度控制、提示词组装、JSON输出、记忆机制、RAG知识注入、思维链、多Agent协作等。', href: 'tools/ai_basics/llm_playground.html', icon: 'fa-solid fa-flask', category: 'advanced_learning', tags: ['AI学习'], isNew: true, iconBg: 'bg-slate-50', iconColor: 'text-slate-600', borderColor: 'slate-200', hoverTextColor: 'text-slate-600', linkColor: 'text-slate-600', badgeStyle: 'bg-slate-100 text-slate-700' },
    { id: 'content_generator_case', name: '内容生成器案例库', desc: '丰富的 AIGC 内容生成案例展示，包含一进一出、多模态、批量处理等多种模式的实战用法。', href: 'tools/ai_basics/内容生成器案例库.html', icon: 'fa-solid fa-book', category: 'advanced_learning', tags: ['AI学习', '案例'], isNew: true, iconBg: 'bg-slate-50', iconColor: 'text-slate-600', borderColor: 'slate-200', hoverTextColor: 'text-slate-600', linkColor: 'text-slate-600', badgeStyle: 'bg-slate-100 text-slate-700' },
    { id: 'models_api_workbench', name: 'Models API 工作台', desc: '配置驱动的 AI 工具生成器。学习 JSON 动态加载与解析，通过 prompts.json 扩展功能。', href: 'tools/models_api/index.html', icon: 'fa-solid fa-puzzle-piece', category: 'advanced_learning', tags: ['动态加载', 'JSON配置', 'Alpine.js'], isNew: true, iconBg: 'bg-indigo-50', iconColor: 'text-indigo-600', borderColor: 'indigo-200', hoverTextColor: 'text-indigo-600', linkColor: 'text-indigo-600', badgeStyle: 'bg-indigo-100 text-indigo-700' },
];
