window.toolCollections = window.toolCollections || {};
window.toolCollections.emotion_station = [
    {
        id: 'cyber_atm',
        name: '赛博提款机',
        desc: '每点一次"提现"余额就增加1个亿！全屏金币暴雨 + AI 生成首富专属问候语',
        href: 'tools/emotion_station/cyber_atm.html',
        icon: 'fa-solid fa-money-bill-trend-up',
        category: 'emotion_station',
        tags: ['小红书'],
        isNew: true,
        complexity: 1,
        iconBg: 'bg-yellow-50',
        iconColor: 'text-yellow-600',
        borderColor: 'yellow-200',
        hoverTextColor: 'text-yellow-600',
        linkColor: 'text-yellow-600'
    },
    {
        id: 'praise_bot',
        name: '夸夸群机器人',
        desc: '分享任何微小成就，AI 从 360 度无死角给你提供高浓度情绪价值赞美',
        href: 'tools/emotion_station/praise_bot.html',
        icon: 'fa-solid fa-face-grin-hearts',
        category: 'emotion_station',
        tags: ['小红书'],
        isNew: true,
        complexity: 1,
        iconBg: 'bg-pink-50',
        iconColor: 'text-pink-600',
        borderColor: 'pink-200',
        hoverTextColor: 'text-pink-600',
        linkColor: 'text-pink-600'
    },
    {
        id: 'emotion_trash',
        name: '情绪垃圾桶',
        desc: '写下负能量，点击发送，文字化作粒子消散。AI 只会说"我都听到了，辛苦了"',
        href: 'tools/emotion_station/emotion_trash.html',
        icon: 'fa-solid fa-trash-can',
        category: 'emotion_station',
        tags: [],
        isNew: true,
        complexity: 1,
        iconBg: 'bg-slate-50',
        iconColor: 'text-slate-600',
        borderColor: 'slate-200',
        hoverTextColor: 'text-slate-600',
        linkColor: 'text-slate-600'
    },
    {
        id: 'wake_up_slap',
        name: '骂醒我清醒剂',
        desc: '输入你明知不该做的事（如联系前任），AI 化身严厉导师狠狠把你骂醒',
        href: 'tools/emotion_station/wake_up_slap.html',
        icon: 'fa-solid fa-hand',
        category: 'emotion_station',
        tags: [],
        isNew: true,
        complexity: 1,
        iconBg: 'bg-red-50',
        iconColor: 'text-red-600',
        borderColor: 'red-200',
        hoverTextColor: 'text-red-600',
        linkColor: 'text-red-600'
    },
    {
        id: 'cyber_muyu',
        name: '赛博电子木鱼',
        desc: '点击敲木鱼，每 100 下 AI 为你生成一句切中心境的禅意开示。功德 +1',
        href: 'tools/emotion_station/cyber_muyu.html',
        icon: 'fa-solid fa-circle-dot',
        category: 'emotion_station',
        tags: ['小红书', '抖音'],
        isNew: true,
        complexity: 1,
        iconBg: 'bg-amber-50',
        iconColor: 'text-amber-600',
        borderColor: 'amber-200',
        hoverTextColor: 'text-amber-600',
        linkColor: 'text-amber-600'
    }
];
