window.toolCollections = window.toolCollections || {};
window.toolCollections.workflow_factory = [
    {
        id: 'content_matrix',
        name: '内容矩阵生成器',
        desc: '一个主题自动拆解为5大平台内容。小红书/公众号/抖音/知乎/微博一键生成，告别重复劳动。',
        href: 'tools/workflow_factory/content_matrix.html',
        icon: 'fa-solid fa-table-cells',
        category: 'workflow_factory',
        tags: ['小红书', '公众号', '抖音', '知乎', '微博'],
        isNew: true,
        complexity: 4,
        iconBg: 'bg-violet-50',
        iconColor: 'text-violet-600',
        borderColor: 'violet-200',
        hoverTextColor: 'text-violet-600',
        linkColor: 'text-violet-600'
    },
    {
        id: 'product_launch_kit',
        name: '产品发布全案',
        desc: '输入产品信息，自动编排生成新闻稿、社交媒体文案包、EDM邮件、FAQ文档，一站式搞定发布日。',
        href: 'tools/workflow_factory/product_launch_kit.html',
        icon: 'fa-solid fa-rocket',
        category: 'workflow_factory',
        tags: ['电商', '公众号', '小红书'],
        isNew: true,
        complexity: 4,
        iconBg: 'bg-purple-50',
        iconColor: 'text-purple-600',
        borderColor: 'purple-200',
        hoverTextColor: 'text-purple-600',
        linkColor: 'text-purple-600'
    },
    {
        id: 'crisis_pr',
        name: '危机公关方案',
        desc: '描述危机事件，AI按步骤编排：舆情分析→回应策略→声明起草→内部通知→后续修复计划。',
        href: 'tools/workflow_factory/crisis_pr.html',
        icon: 'fa-solid fa-shield-halved',
        category: 'workflow_factory',
        tags: ['公众号', '微博'],
        isNew: true,
        complexity: 5,
        iconBg: 'bg-red-50',
        iconColor: 'text-red-600',
        borderColor: 'red-200',
        hoverTextColor: 'text-red-600',
        linkColor: 'text-red-600'
    },
    {
        id: 'event_planner',
        name: '活动策划全案',
        desc: '活动类型+目标+预算→创意概念→执行方案→宣传文案包→预算分配→时间线，全流程编排。',
        href: 'tools/workflow_factory/event_planner.html',
        icon: 'fa-solid fa-calendar-check',
        category: 'workflow_factory',
        tags: ['私域', '公众号'],
        isNew: true,
        complexity: 4,
        iconBg: 'bg-indigo-50',
        iconColor: 'text-indigo-600',
        borderColor: 'indigo-200',
        hoverTextColor: 'text-indigo-600',
        linkColor: 'text-indigo-600'
    },
    {
        id: 'brand_full_plan',
        name: '品牌全案策划',
        desc: '从品牌定位出发，依次编排品牌故事→视觉风格建议→内容策略→传播计划→执行时间表。',
        href: 'tools/workflow_factory/brand_full_plan.html',
        icon: 'fa-solid fa-gem',
        category: 'workflow_factory',
        tags: ['小红书', '公众号', '抖音'],
        isNew: true,
        complexity: 5,
        iconBg: 'bg-amber-50',
        iconColor: 'text-amber-600',
        borderColor: 'amber-200',
        hoverTextColor: 'text-amber-600',
        linkColor: 'text-amber-600'
    }
];
