window.toolCollections = window.toolCollections || {};
window.toolCollections.social_er = [
    {
        id: 'pua_detector',
        name: '渣男/绿茶鉴定中心',
        desc: '把对象说的话丢进来，AI 分析 PUA 浓度、服从性测试和养鱼概率，紧急拔智齿',
        href: 'tools/social_er/pua_detector.html',
        icon: 'fa-solid fa-magnifying-glass',
        category: 'social_er',
        tags: ['小红书'],
        isNew: true,
        complexity: 1,
        iconBg: 'bg-rose-50',
        iconColor: 'text-rose-600',
        borderColor: 'rose-200',
        hoverTextColor: 'text-rose-600',
        linkColor: 'text-rose-600'
    },
    {
        id: 'comeback_king',
        name: 'AI 最强嘴替',
        desc: '粘贴聊天记录，选阴阳怪气/祖安/大女主/讲理/佛系与火力强度，AI 流式生成 3 条带杀伤力星级的回击',
        href: 'tools/social_er/comeback_king.html',
        icon: 'fa-solid fa-fire',
        category: 'social_er',
        tags: ['小红书'],
        isNew: true,
        complexity: 1,
        iconBg: 'bg-orange-50',
        iconColor: 'text-orange-600',
        borderColor: 'orange-200',
        hoverTextColor: 'text-orange-600',
        linkColor: 'text-orange-600'
    },
    {
        id: 'pet_translator',
        name: '猫狗心声翻译器',
        desc: '描述宠物当前状态，AI 用三分薄凉三分讥笑的语气生成宠物对你的内心吐槽',
        href: 'tools/social_er/pet_translator.html',
        icon: 'fa-solid fa-cat',
        category: 'social_er',
        tags: ['小红书', '抖音'],
        isNew: true,
        complexity: 1,
        iconBg: 'bg-amber-50',
        iconColor: 'text-amber-600',
        borderColor: 'amber-200',
        hoverTextColor: 'text-amber-600',
        linkColor: 'text-amber-600'
    },
    {
        id: 'drama_coin',
        name: '决定硬币（加戏版）',
        desc: '输入两个纠结选项，抛硬币决定命运。AI 用极具说服力的理由让你心服口服',
        href: 'tools/social_er/drama_coin.html',
        icon: 'fa-solid fa-coins',
        category: 'social_er',
        tags: [],
        isNew: true,
        complexity: 1,
        iconBg: 'bg-yellow-50',
        iconColor: 'text-yellow-600',
        borderColor: 'yellow-200',
        hoverTextColor: 'text-yellow-600',
        linkColor: 'text-yellow-600'
    },
    {
        id: 'fanfic_machine',
        name: '同人文生成器',
        desc: '输入角色名和 CP 属性，AI 在本地源源不断生成专属小说。没有审核，无限续杯',
        href: 'tools/social_er/fanfic_machine.html',
        icon: 'fa-solid fa-heart',
        category: 'social_er',
        tags: [],
        isNew: true,
        complexity: 2,
        iconBg: 'bg-pink-50',
        iconColor: 'text-pink-600',
        borderColor: 'pink-200',
        hoverTextColor: 'text-pink-600',
        linkColor: 'text-pink-600'
    }
];
