window.toolCollections = window.toolCollections || {};
window.toolCollections.cyber_mystic = [
    {
        id: 'epitaph_box',
        name: '赛博墓志铭盲盒',
        desc: '输入你今天荒废了多少时间，AI 用黑色幽默告诉你墓碑上会被刻什么耻辱句子',
        href: 'tools/cyber_mystic/epitaph_box.html',
        icon: 'fa-solid fa-skull',
        category: 'cyber_mystic',
        tags: ['小红书'],
        isNew: true,
        complexity: 1,
        iconBg: 'bg-slate-50',
        iconColor: 'text-slate-600',
        borderColor: 'slate-200',
        hoverTextColor: 'text-slate-600',
        linkColor: 'text-slate-600'
    },
    {
        id: 'my_wikipedia',
        name: '"我的维基百科"词条',
        desc: '输入你的平凡经历，AI 用标准维基百科体为你生成一个严肃的个人词条页面',
        href: 'tools/cyber_mystic/my_wikipedia.html',
        icon: 'fa-solid fa-globe',
        category: 'cyber_mystic',
        tags: ['小红书'],
        isNew: true,
        complexity: 2,
        iconBg: 'bg-blue-50',
        iconColor: 'text-blue-600',
        borderColor: 'blue-200',
        hoverTextColor: 'text-blue-600',
        linkColor: 'text-blue-600'
    },
    {
        id: 'mood_color',
        name: '情绪调色盘',
        desc: '输入今天的心情文字，AI 将其转为一种颜色代码，整个页面背景瞬间变成你的情绪色',
        href: 'tools/cyber_mystic/mood_color.html',
        icon: 'fa-solid fa-droplet',
        category: 'cyber_mystic',
        tags: ['小红书'],
        isNew: true,
        complexity: 1,
        iconBg: 'bg-violet-50',
        iconColor: 'text-violet-600',
        borderColor: 'violet-200',
        hoverTextColor: 'text-violet-600',
        linkColor: 'text-violet-600'
    },
    {
        id: 'voodoo_doll',
        name: '赛博扎小人画板',
        desc: '画一个火柴人，选武器猛击，AI 生成武侠小说式的痛殴战斗播报。超级解压！',
        href: 'tools/cyber_mystic/voodoo_doll.html',
        icon: 'fa-solid fa-crosshairs',
        category: 'cyber_mystic',
        tags: ['抖音'],
        isNew: true,
        complexity: 2,
        iconBg: 'bg-red-50',
        iconColor: 'text-red-600',
        borderColor: 'red-200',
        hoverTextColor: 'text-red-600',
        linkColor: 'text-red-600'
    },
    {
        id: 'cyber_fortune_stick',
        name: '赛博解签',
        desc: '摇签筒抽签，AI 结合现代打工人处境用半文半白为你开解。求签问卦，赛博灵验',
        href: 'tools/cyber_mystic/cyber_fortune_stick.html',
        icon: 'fa-solid fa-wand-sparkles',
        category: 'cyber_mystic',
        tags: ['小红书', '抖音'],
        isNew: true,
        complexity: 1,
        iconBg: 'bg-amber-50',
        iconColor: 'text-amber-600',
        borderColor: 'amber-200',
        hoverTextColor: 'text-amber-600',
        linkColor: 'text-amber-600'
    }
];
