window.toolCollections = window.toolCollections || {};
window.toolCollections.doc_transform = [
    {
        id: 'summary_chain',
        name: '长文摘要链',
        desc: '粘贴长文→分段摘要→整体摘要→关键要点→思维导图→社交媒体版本，一篇文章N种用途。',
        href: 'tools/doc_transform/summary_chain.html',
        icon: 'fa-solid fa-link',
        category: 'doc_transform',
        tags: ['公众号', '知乎', '小红书'],
        isNew: true,
        complexity: 3,
        iconBg: 'bg-amber-50',
        iconColor: 'text-amber-600',
        borderColor: 'amber-200',
        hoverTextColor: 'text-amber-600',
        linkColor: 'text-amber-600'
    },
    {
        id: 'reading_notes_chain',
        name: '读书笔记链',
        desc: '粘贴书摘/划线→提炼核心观点→生成思维导图→写读后感→小红书分享版，读书笔记一条龙。',
        href: 'tools/doc_transform/reading_notes_chain.html',
        icon: 'fa-solid fa-book-bookmark',
        category: 'doc_transform',
        tags: ['小红书', '公众号', '知乎'],
        isNew: true,
        complexity: 3,
        iconBg: 'bg-emerald-50',
        iconColor: 'text-emerald-600',
        borderColor: 'emerald-200',
        hoverTextColor: 'text-emerald-600',
        linkColor: 'text-emerald-600'
    },
    {
        id: 'paper_to_popular',
        name: '论文转科普',
        desc: '粘贴学术论文摘要→通俗解读→博客文章版→社交媒体版→短视频脚本版，学术成果大众化。',
        href: 'tools/doc_transform/paper_to_popular.html',
        icon: 'fa-solid fa-graduation-cap',
        category: 'doc_transform',
        tags: ['知乎', '公众号', '短视频'],
        isNew: true,
        complexity: 4,
        iconBg: 'bg-blue-50',
        iconColor: 'text-blue-600',
        borderColor: 'blue-200',
        hoverTextColor: 'text-blue-600',
        linkColor: 'text-blue-600'
    },
    {
        id: 'meeting_to_action',
        name: '会议纪要转行动',
        desc: '粘贴会议记录→提炼决议→分解待办事项→生成跟进邮件→下次会议议程，会后高效执行。',
        href: 'tools/doc_transform/meeting_to_action.html',
        icon: 'fa-solid fa-list-check',
        category: 'doc_transform',
        tags: ['职场'],
        isNew: true,
        complexity: 3,
        iconBg: 'bg-sky-50',
        iconColor: 'text-sky-600',
        borderColor: 'sky-200',
        hoverTextColor: 'text-sky-600',
        linkColor: 'text-sky-600'
    },
    {
        id: 'requirement_to_prd',
        name: '需求转PRD',
        desc: '粗略需求描述→用户故事→验收标准→功能优先级矩阵→完整PRD文档，产品经理效率工具。',
        href: 'tools/doc_transform/requirement_to_prd.html',
        icon: 'fa-solid fa-file-lines',
        category: 'doc_transform',
        tags: ['职场'],
        isNew: true,
        complexity: 4,
        iconBg: 'bg-indigo-50',
        iconColor: 'text-indigo-600',
        borderColor: 'indigo-200',
        hoverTextColor: 'text-indigo-600',
        linkColor: 'text-indigo-600'
    }
];
