window.toolCollections = window.toolCollections || {};
window.toolCollections.creative_box = [
    {
        id: 'decision_advisor',
        name: '决策顾问',
        desc: '多角度决策分析。从理性、情感、风险、长期后果等多个维度帮你剖析重大决策。',
        href: 'tools/creative_box/decision_advisor.html',
        icon: 'fa-solid fa-compass',
        category: 'creative_box',
        tags: ['决策', '思维'],
        isNew: true,
        iconBg: 'bg-indigo-50',
        iconColor: 'text-indigo-600',
        borderColor: 'indigo-200',
        hoverTextColor: 'text-indigo-600',
        linkColor: 'text-indigo-600',
        badgeStyle: 'bg-indigo-100 text-indigo-700'
    },
    {
        id: 'knowledge_builder',
        name: '知识体系构建器',
        desc: '打造你的第二大脑。输入你想精通的领域，AI 帮你构建系统的知识框架和学习路径。',
        href: 'tools/creative_box/knowledge_builder.html',
        icon: 'fa-solid fa-network',
        category: 'creative_box',
        tags: ['知识', '体系'],
        isNew: true,
        iconBg: 'bg-purple-50',
        iconColor: 'text-purple-600',
        borderColor: 'purple-200',
        hoverTextColor: 'text-purple-600',
        linkColor: 'text-purple-600',
        badgeStyle: 'bg-purple-100 text-purple-700'
    },
    {
        id: 'first_principles',
        name: '第一性原理思考器',
        desc: '打破常规的思维训练。引导你拆解问题到最基本的事实，重构解决方案。',
        href: 'tools/creative_box/first_principles.html',
        icon: 'fa-solid fa-atom',
        category: 'creative_box',
        tags: ['思维', '创新'],
        iconBg: 'bg-blue-50',
        iconColor: 'text-blue-600',
        borderColor: 'blue-200',
        hoverTextColor: 'text-blue-600',
        linkColor: 'text-blue-600'
    },
    {
        id: 'analogy_master',
        name: '类比思维大师',
        desc: '复杂概念通俗化。输入难懂的概念，AI 生成生动的类比和比喻帮助理解。',
        href: 'tools/creative_box/analogy_master.html',
        icon: 'fa-solid fa-copy',
        category: 'creative_box',
        tags: ['思维', '学习'],
        iconBg: 'bg-cyan-50',
        iconColor: 'text-cyan-600',
        borderColor: 'cyan-200',
        hoverTextColor: 'text-cyan-600',
        linkColor: 'text-cyan-600'
    },
    {
        id: 'cognitive_bias_detector',
        name: '认知偏差探测器',
        desc: '决策纠偏工具。输入你的想法或论证，AI 帮你识别其中可能存在的认知偏差。',
        href: 'tools/creative_box/cognitive_bias_detector.html',
        icon: 'fa-solid fa-eye',
        category: 'creative_box',
        tags: ['思维', '心理'],
        iconBg: 'bg-red-50',
        iconColor: 'text-red-600',
        borderColor: 'red-200',
        hoverTextColor: 'text-red-600',
        linkColor: 'text-red-600'
    },
    {
        id: 'career_path_planner',
        name: '职业路径模拟器',
        desc: '探索职业发展的无限可能。基于你的技能和兴趣，AI 推演多条职业发展路线。',
        href: 'tools/creative_box/career_path_planner.html',
        icon: 'fa-solid fa-map',
        category: 'creative_box',
        tags: ['职业', '规划'],
        iconBg: 'bg-violet-50',
        iconColor: 'text-violet-600',
        borderColor: 'violet-200',
        hoverTextColor: 'text-violet-600',
        linkColor: 'text-violet-600'
    },
    {
        id: 'book_relationship_graph',
        name: '书籍关系图谱',
        desc: '输入书名，AI 自动生成人物关系图、概念脉络图。',
        href: 'tools/creative_box/book_relationship_graph.html',
        icon: 'fa-solid fa-book-bookmark',
        category: 'creative_box',
        tags: ['阅读', '知识图谱'],
        iconBg: 'bg-amber-50',
        iconColor: 'text-amber-600',
        borderColor: 'amber-200',
        hoverTextColor: 'text-amber-600',
        linkColor: 'text-amber-600'
    },
    {
        id: 'concept_visualizer',
        name: '概念可视化工具',
        desc: '将抽象概念转化为可视化图表，让思想一目了然。',
        href: 'tools/creative_box/concept_visualizer.html',
        icon: 'fa-solid fa-image',
        category: 'creative_box',
        tags: ['思维', '可视化'],
        iconBg: 'bg-pink-50',
        iconColor: 'text-pink-600',
        borderColor: 'pink-200',
        hoverTextColor: 'text-pink-600',
        linkColor: 'text-pink-600'
    },
    {
        id: 'contrarian_thinker',
        name: '逆向思维训练器',
        desc: '挑战常识，发现盲点。AI 扮演反方，训练你的批判性思维能力。',
        href: 'tools/creative_box/contrarian_thinker.html',
        icon: 'fa-solid fa-undo',
        category: 'creative_box',
        tags: ['思维', '辩论'],
        iconBg: 'bg-stone-50',
        iconColor: 'text-stone-600',
        borderColor: 'stone-200',
        hoverTextColor: 'text-stone-600',
        linkColor: 'text-stone-600'
    },
    {
        id: 'corporate_jargon_translator',
        name: '黑话翻译器',
        desc: '互联网黑话/职场术语一键翻译成人话。',
        href: 'tools/creative_box/corporate_jargon_translator.html',
        icon: 'fa-solid fa-language',
        category: 'creative_box',
        tags: ['职场', '趣味'],
        iconBg: 'bg-gray-50',
        iconColor: 'text-gray-600',
        borderColor: 'gray-200',
        hoverTextColor: 'text-gray-600',
        linkColor: 'text-gray-600'
    },
    {
        id: 'crisis_pr_simulator',
        name: '危机公关模拟器',
        desc: '公关危机突发！你将如何应对？模拟真实舆情环境，考验你的危机处理能力。',
        href: 'tools/creative_box/crisis_pr_simulator.html',
        icon: 'fa-solid fa-shield-halved',
        category: 'creative_box',
        tags: ['公关', '模拟'],
        iconBg: 'bg-rose-50',
        iconColor: 'text-rose-600',
        borderColor: 'rose-200',
        hoverTextColor: 'text-rose-600',
        linkColor: 'text-rose-600'
    },
    {
        id: 'decision_matrix',
        name: '决策矩阵工具',
        desc: '加权决策矩阵。量化评估多个选项，做出更理性的选择。',
        href: 'tools/creative_box/decision_matrix.html',
        icon: 'fa-solid fa-table-cells',
        category: 'creative_box',
        tags: ['决策', '效率'],
        iconBg: 'bg-blue-50',
        iconColor: 'text-blue-600',
        borderColor: 'blue-200',
        hoverTextColor: 'text-blue-600',
        linkColor: 'text-blue-600'
    },
    {
        id: 'excuse_generator',
        name: '请假/借口生成器',
        desc: '高情商理由生成。无论是请假、迟到还是拒绝邀请，AI 帮你从容应对。',
        href: 'tools/creative_box/excuse_generator.html',
        icon: 'fa-solid fa-smile',
        category: 'creative_box',
        tags: ['趣味', '职场'],
        iconBg: 'bg-yellow-50',
        iconColor: 'text-yellow-600',
        borderColor: 'yellow-200',
        hoverTextColor: 'text-yellow-600',
        linkColor: 'text-yellow-600'
    },
    {
        id: 'finance_sandbox',
        name: '个人财务沙盘',
        desc: '模拟未来财务状况。推演不同投资消费策略下的财富积累路径。',
        href: 'tools/creative_box/finance_sandbox.html',
        icon: 'fa-solid fa-coins',
        category: 'creative_box',
        tags: ['理财', '规划'],
        iconBg: 'bg-emerald-50',
        iconColor: 'text-emerald-600',
        borderColor: 'emerald-200',
        hoverTextColor: 'text-emerald-600',
        linkColor: 'text-emerald-600'
    },
    {
        id: 'habit_designer',
        name: '微习惯设计器',
        desc: '科学养成好习惯。基于行为心理学，帮你设计易于坚持的微小行动。',
        href: 'tools/creative_box/habit_designer.html',
        icon: 'fa-solid fa-check-circle',
        category: 'creative_box',
        tags: ['习惯', '成长'],
        iconBg: 'bg-teal-50',
        iconColor: 'text-teal-600',
        borderColor: 'teal-200',
        hoverTextColor: 'text-teal-600',
        linkColor: 'text-teal-600'
    },
    {
        id: 'interview_simulator',
        name: '模拟面试官',
        desc: '真实面试场景模拟。AI 扮演面试官，提供针对性提问和反馈建议。',
        href: 'tools/creative_box/interview_simulator.html',
        icon: 'fa-solid fa-user-tie',
        category: 'creative_box',
        tags: ['面试', '求职'],
        iconBg: 'bg-blue-50',
        iconColor: 'text-blue-600',
        borderColor: 'blue-200',
        hoverTextColor: 'text-blue-600',
        linkColor: 'text-blue-600'
    },
    {
        id: 'learning_buddy',
        name: '交互式学习伴侣',
        desc: '苏格拉底式教学。AI 通过提问引导你深入思考，而非直接给出答案。',
        href: 'tools/creative_box/learning_buddy.html',
        icon: 'fa-solid fa-robot',
        category: 'creative_box',
        tags: ['学习', '教育'],
        iconBg: 'bg-green-50',
        iconColor: 'text-green-600',
        borderColor: 'green-200',
        hoverTextColor: 'text-green-600',
        linkColor: 'text-green-600'
    },
    {
        id: 'learning_path_planner',
        name: '学习路径规划师',
        desc: '定制个性化学习路线图。从入门到精通，规划清晰的学习阶段和资源。',
        href: 'tools/creative_box/learning_path_planner.html',
        icon: 'fa-solid fa-route',
        category: 'creative_box',
        tags: ['学习', '规划'],
        iconBg: 'bg-indigo-50',
        iconColor: 'text-indigo-600',
        borderColor: 'indigo-200',
        hoverTextColor: 'text-indigo-600',
        linkColor: 'text-indigo-600'
    },
    {
        id: 'logo_concept_designer',
        name: 'Logo 概念设计师',
        desc: '品牌视觉创意生成。输入品牌理念，生成 Logo 设计概念和草图描述。',
        href: 'tools/creative_box/logo_concept_designer.html',
        icon: 'fa-solid fa-pen-nib',
        category: 'creative_box',
        tags: ['设计', '品牌'],
        iconBg: 'bg-orange-50',
        iconColor: 'text-orange-600',
        borderColor: 'orange-200',
        hoverTextColor: 'text-orange-600',
        linkColor: 'text-orange-600'
    },
    {
        id: 'metaphor_generator',
        name: '隐喻生成器',
        desc: '让表达更生动。AI 为你生成富有创意的隐喻和比拟，提升文案渲染力。',
        href: 'tools/creative_box/metaphor_generator.html',
        icon: 'fa-solid fa-wand-magic-sparkles',
        category: 'creative_box',
        tags: ['写作', '修辞'],
        iconBg: 'bg-fuchsia-50',
        iconColor: 'text-fuchsia-600',
        borderColor: 'fuchsia-200',
        hoverTextColor: 'text-fuchsia-600',
        linkColor: 'text-fuchsia-600'
    },
    {
        id: 'negotiation_trainer',
        name: '谈判教练',
        desc: '模拟真实谈判博弈。AI 扮演谈判对手，训练你的沟通技巧和议价能力。',
        href: 'tools/creative_box/negotiation_trainer.html',
        icon: 'fa-solid fa-users',
        category: 'creative_box',
        tags: ['谈判', '职场'],
        iconBg: 'bg-slate-50',
        iconColor: 'text-slate-600',
        borderColor: 'slate-200',
        hoverTextColor: 'text-slate-600',
        linkColor: 'text-slate-600'
    },
    {
        id: 'what_if_history',
        name: '历史假设模拟器',
        desc: '重写历史的可能性。如果历史上的关键事件发生改变，世界会变成什么样？',
        href: 'tools/creative_box/what_if_history.html',
        icon: 'fa-solid fa-hourglass',
        category: 'creative_box',
        tags: ['历史', '脑洞'],
        iconBg: 'bg-stone-50',
        iconColor: 'text-stone-700',
        borderColor: 'stone-200',
        hoverTextColor: 'text-stone-700',
        linkColor: 'text-stone-700'
    }
];
