window.toolCollections = window.toolCollections || {};
window.toolCollections['xhs-tools'] = [
    {
        id: 'xhs_generator',
        name: '批量文案专家',
        desc: '一次生成多个选题及其对应文案。支持批量生成正文，快速构建小红书内容矩阵。',
        href: 'tools/xhs-tools/xhs_generator.html',
        icon: 'fa-solid fa-lightbulb',
        category: 'xhs-tools',
        tags: ['小红书', '选题', '内容创作', '批量生成'],
        isNew: false,
        iconBg: 'bg-yellow-50',
        iconColor: 'text-yellow-600',
        borderColor: 'yellow-200',
        hoverTextColor: 'text-yellow-600',
        linkColor: 'text-yellow-600'
    },
    {
        id: 'xhs_topic_analyzer',
        name: '选题拆解分析大师',
        desc: '拆解爆款内容，分析热词、钩子、情绪及痛点。深度拆解爆款笔记的成功要素。',
        href: 'tools/xhs-tools/xhs_topic_analyzer.html',
        icon: 'fa-solid fa-magnifying-glass',
        category: 'xhs-tools',
        tags: ['小红书', '选题分析', '内容拆解'],
        isNew: false,
        iconBg: 'bg-blue-50',
        iconColor: 'text-blue-600',
        borderColor: 'blue-200',
        hoverTextColor: 'text-blue-600',
        linkColor: 'text-blue-600'
    },
    {
        id: 'xhs_polisher',
        name: '小红书文案润色器',
        desc: '多选改写方向，自动优化排版、表情和标题。支持语气调整和内容精简。',
        href: 'tools/xhs-tools/xhs_polisher.html',
        icon: 'fa-solid fa-paintbrush',
        category: 'xhs-tools',
        tags: ['小红书', '润色', '排版'],
        isNew: false,
        iconBg: 'bg-rose-50',
        iconColor: 'text-rose-600',
        borderColor: 'rose-200',
        hoverTextColor: 'text-rose-600',
        linkColor: 'text-rose-600'
    },
    {
        id: 'xhs_html_card_generator',
        name: '小红书 HTML 卡片生成器',
        desc: '文字转精美图片卡片，支持缩放预览和动画效果。生成可直接保存的图片。',
        href: 'tools/xhs-tools/xhs_html_card_generator.html',
        icon: 'fa-solid fa-credit-card',
        category: 'xhs-tools',
        tags: ['小红书', '卡片', '图片生成'],
        isNew: false,
        iconBg: 'bg-green-50',
        iconColor: 'text-green-600',
        borderColor: 'green-200',
        hoverTextColor: 'text-green-600',
        linkColor: 'text-green-600'
    },

    {
        id: 'xhs_cover_layout_generator',
        name: '小红书封面布局生成器',
        desc: '多种封面布局模板，一键生成专业封面。支持文字位置和样式调整。',
        href: 'tools/xhs-tools/xhs_cover_layout_generator.html',
        icon: 'fa-solid fa-layer-group',
        category: 'xhs-tools',
        tags: ['小红书', '封面', '布局'],
        isNew: false,
        iconBg: 'bg-indigo-50',
        iconColor: 'text-indigo-600',
        borderColor: 'indigo-200',
        hoverTextColor: 'text-indigo-600',
        linkColor: 'text-indigo-600'
    },
    {
        id: 'xhs_card_splitter',
        name: '小红书卡片分割器',
        desc: '将长图分割为单张卡片。支持自定义分割数量，快速生成系列内容。',
        href: 'tools/xhs-tools/xhs_card_splitter.html',
        icon: 'fa-solid fa-scissors',
        category: 'xhs-tools',
        tags: ['小红书', '图片处理', '分割'],
        isNew: false,
        iconBg: 'bg-teal-50',
        iconColor: 'text-teal-600',
        borderColor: 'teal-200',
        hoverTextColor: 'text-teal-600',
        linkColor: 'text-teal-600'
    }
];
