window.toolCollections = window.toolCollections || {};
window.toolCollections.growth = [
    { id: 'flashcard_generator', name: '记忆卡片生成器', desc: '学习提效工具。输入单词或知识点，生成包含释义、例句、记忆钩子的 Anki 卡片，支持 CSV 导出。', href: 'tools/growth/flashcard_generator.html', icon: 'fa-solid fa-note-sticky', category: 'growth', tags: ['学习', '记忆'], isNew: true, iconBg: 'bg-teal-50', iconColor: 'text-teal-600', borderColor: 'teal-200', hoverTextColor: 'text-teal-600', linkColor: 'text-teal-600', badgeStyle: 'bg-teal-100 text-teal-700' },
    { id: 'communication_master', name: '高情商沟通助手', desc: '职场/人际救星。输入真实想法（如"不想借钱"），AI 生成得体、高情商的回复话术。支持R1心理分析。', href: 'tools/growth/communication_master.html', icon: 'fa-solid fa-comment-dots', category: 'growth', tags: ['沟通', '情商'], isNew: true, iconBg: 'bg-pink-50', iconColor: 'text-pink-600', borderColor: 'pink-200', hoverTextColor: 'text-pink-600', linkColor: 'text-pink-600', badgeStyle: 'bg-pink-100 text-pink-700' },
    { id: 'gift_ideas', name: '送礼指南针', desc: '解决送礼头秃。根据关系、预算、场合定制灵感清单，并配好温馨贺卡词。', href: 'tools/growth/gift_ideas.html', icon: 'fa-solid fa-gift', category: 'growth', tags: ['社交', '生活'], isNew: true, iconBg: 'bg-rose-50', iconColor: 'text-rose-600', borderColor: 'rose-200', hoverTextColor: 'text-rose-600', linkColor: 'text-rose-600' },
    { id: 'compliment_gen', name: '夸夸生成器', desc: '情绪价值拉满。不管是工作受挫还是生活委屈，AI 变着花样夸你，给你最温暖的治愈。', href: 'tools/growth/compliment_gen.html', icon: 'fa-solid fa-sun', category: 'growth', tags: ['治愈', '情绪'], isNew: true, iconBg: 'bg-amber-50', iconColor: 'text-amber-600', borderColor: 'amber-200', hoverTextColor: 'text-amber-600', linkColor: 'text-amber-600' },
    { id: 'conflict_resolver', name: '吵架复盘/和事佬', desc: '理性化解冲突。输入争吵内容，AI 分析双方核心诉求，提供高情商和解方案。', href: 'tools/growth/conflict_resolver.html', icon: 'fa-solid fa-shield-halved', category: 'growth', tags: ['情感', '社交'], isNew: true, iconBg: 'bg-indigo-50', iconColor: 'text-indigo-600', borderColor: 'indigo-200', hoverTextColor: 'text-indigo-600', linkColor: 'text-indigo-600' },
    { id: 'reverse_question_breaker', name: '逆向问题拆解器', desc: '用反向问题打破思维惯性，快速找到新切入点。', href: 'tools/growth/reverse_question_breaker.html', icon: 'fa-solid fa-repeat', category: 'growth', tags: ['思考', '启发'], isNew: true, iconBg: 'bg-slate-50', iconColor: 'text-slate-700', borderColor: 'slate-200', hoverTextColor: 'text-slate-700', linkColor: 'text-slate-700', badgeStyle: 'bg-slate-100 text-slate-700' },
    { id: 'future_gratitude_decision', name: '三年后会感谢的决定', desc: 'AI 推演三年时间线，帮你想象长期回报。', href: 'tools/growth/future_gratitude_decision.html', icon: 'fa-solid fa-clock', category: 'growth', tags: ['思考', '决策'], isNew: true, iconBg: 'bg-pink-50', iconColor: 'text-pink-600', borderColor: 'pink-200', hoverTextColor: 'text-pink-600', linkColor: 'text-pink-600', badgeStyle: 'bg-pink-100 text-pink-700' },
    { id: 'weekly_energy_budget', name: '本周能量预算', desc: '输入一周任务与能量消耗，生成预算曲线与建议。', href: 'tools/growth/weekly_energy_budget.html', icon: 'fa-solid fa-battery-full', category: 'growth', tags: ['生活', '效率'], isNew: true, iconBg: 'bg-lime-50', iconColor: 'text-lime-600', borderColor: 'lime-200', hoverTextColor: 'text-lime-600', linkColor: 'text-lime-600', badgeStyle: 'bg-lime-100 text-lime-700' },
    { id: 'quest_breaker', name: '任务冒险拆解器', desc: '游戏化目标管理工具。将待办事项转化为RPG冒险任务，拆解打怪目标、设计Boss关卡、规划阶段奖励，让枯燥任务变得有趣！', href: 'tools/growth/quest_breaker.html', icon: 'fa-solid fa-fire', category: 'growth', tags: ['游戏化', '目标管理', 'V4 Pro 推理'], isNew: true, iconBg: 'bg-purple-50', iconColor: 'text-purple-600', borderColor: 'purple-200', hoverTextColor: 'text-purple-600', linkColor: 'text-purple-600', badgeStyle: 'bg-purple-100 text-purple-700' },
    { id: 'social_rehearsal', name: '社交情景彩排', desc: '社恐福音。模拟高难度社交场景（如拒绝请求、谈判、搭讪），AI 陪你反复练习对话，提供实时反馈与建议。', href: 'tools/growth/social_rehearsal.html', icon: 'fa-solid fa-users', category: 'growth', tags: ['沟通', '社交'], isNew: true, iconBg: 'bg-green-50', iconColor: 'text-green-600', borderColor: 'green-200', hoverTextColor: 'text-green-600', linkColor: 'text-green-600', badgeStyle: 'bg-green-100 text-green-700' },
    { id: 'focus_battle', name: '专注对战计时器', desc: '游戏化番茄钟。与 AI 或虚拟对手进行"专注力PK"，保持专注获得攻击力，分心则掉血，让工作学习变成一场战斗。', href: 'tools/growth/focus_battle.html', icon: 'fa-solid fa-fire', category: 'growth', tags: ['专注', '游戏化'], isNew: true, iconBg: 'bg-red-50', iconColor: 'text-red-600', borderColor: 'red-200', hoverTextColor: 'text-red-600', linkColor: 'text-red-600', badgeStyle: 'bg-red-100 text-red-700' },
    { id: 'habit_lab', name: '习惯实验室', desc: '科学养成好习惯。基于行为设计学，拆解习惯回路（提示-渴求-反应-奖赏），记录并优化你的微习惯。', href: 'tools/growth/habit_lab.html', icon: 'fa-solid fa-flask', category: 'growth', tags: ['习惯', '自律'], isNew: true, iconBg: 'bg-indigo-50', iconColor: 'text-indigo-600', borderColor: 'indigo-200', hoverTextColor: 'text-indigo-600', linkColor: 'text-indigo-600', badgeStyle: 'bg-indigo-100 text-indigo-700' },
];
