window.toolCollections = window.toolCollections || {};
window.toolCollections.edu_training = [
    {
        id: 'course_outline',
        name: '课程大纲编排器',
        desc: '主题+目标受众+总时长→拆解知识模块→调整顺序→细化每课时（目标/内容/互动/作业）→导出完整大纲。',
        href: 'tools/edu_training/course_outline.html',
        icon: 'fa-solid fa-chalkboard-user',
        category: 'edu_training',
        tags: ['公众号'],
        isNew: true,
        complexity: 4,
        iconBg: 'bg-emerald-50',
        iconColor: 'text-emerald-600',
        borderColor: 'emerald-200',
        hoverTextColor: 'text-emerald-600',
        linkColor: 'text-emerald-600'
    },
    {
        id: 'exam_generator',
        name: '考试出题器',
        desc: '知识范围+题型+难度→批量生成题目→筛选→补充答案解析+评分标准→导出试卷+答案。',
        href: 'tools/edu_training/exam_generator.html',
        icon: 'fa-solid fa-clipboard-question',
        category: 'edu_training',
        tags: [],
        isNew: true,
        complexity: 3,
        iconBg: 'bg-blue-50',
        iconColor: 'text-blue-600',
        borderColor: 'blue-200',
        hoverTextColor: 'text-blue-600',
        linkColor: 'text-blue-600'
    },
    {
        id: 'lesson_plan_gen',
        name: '教案生成器',
        desc: '课题+年级+课时→教学目标→教学活动设计→板书/PPT要点→课后作业，新手老师必备。',
        href: 'tools/edu_training/lesson_plan_gen.html',
        icon: 'fa-solid fa-book-open-reader',
        category: 'edu_training',
        tags: [],
        isNew: true,
        complexity: 3,
        iconBg: 'bg-orange-50',
        iconColor: 'text-orange-600',
        borderColor: 'orange-200',
        hoverTextColor: 'text-orange-600',
        linkColor: 'text-orange-600'
    },
    {
        id: 'knowledge_map',
        name: '知识图谱构建器',
        desc: '输入领域/课题→提取核心概念→构建概念关系→生成Mermaid知识图谱→标注学习路径。',
        href: 'tools/edu_training/knowledge_map.html',
        icon: 'fa-solid fa-diagram-project',
        category: 'edu_training',
        tags: [],
        isNew: true,
        complexity: 4,
        iconBg: 'bg-violet-50',
        iconColor: 'text-violet-600',
        borderColor: 'violet-200',
        hoverTextColor: 'text-violet-600',
        linkColor: 'text-violet-600'
    },
    {
        id: 'error_analyzer',
        name: '错题分析师',
        desc: '粘贴错题→诊断知识薄弱点→归类错误类型→生成针对性练习题+知识点讲解，精准补短板。',
        href: 'tools/edu_training/error_analyzer.html',
        icon: 'fa-solid fa-magnifying-glass-chart',
        category: 'edu_training',
        tags: [],
        isNew: true,
        complexity: 3,
        iconBg: 'bg-rose-50',
        iconColor: 'text-rose-600',
        borderColor: 'rose-200',
        hoverTextColor: 'text-rose-600',
        linkColor: 'text-rose-600'
    }
];
