window.toolCollections = window.toolCollections || {};
window.toolCollections.word_playground = [
    {
        id: 'poetry_master',
        name: 'AI 对联/藏头诗大师',
        desc: '对联、藏头诗、五言绝句、七言律诗、打油诗；DeepSeek 流式生成，宣纸风展示、竖排对联、卡片导出。',
        href: 'tools/word_playground/poetry_master.html',
        icon: 'fa-solid fa-scroll',
        category: 'word_playground',
        tags: ['公众号', '小红书'],
        isNew: true,
        complexity: 2,
        iconBg: 'bg-red-50',
        iconColor: 'text-red-600',
        borderColor: 'red-200',
        hoverTextColor: 'text-red-600',
        linkColor: 'text-red-600'
    },
    {
        id: 'micro_story',
        name: '一句话小说',
        desc: '给出一句话，AI 流式扩写微型小说（100/300/500 字）。类型含悬疑、科幻、爱情、恐怖、温情、荒诞、反转；支持换结局、复制与导出。',
        href: 'tools/word_playground/micro_story.html',
        icon: 'fa-solid fa-feather-pointed',
        category: 'word_playground',
        tags: ['公众号', '知乎'],
        isNew: true,
        complexity: 1,
        iconBg: 'bg-amber-50',
        iconColor: 'text-amber-600',
        borderColor: 'amber-200',
        hoverTextColor: 'text-amber-600',
        linkColor: 'text-amber-600'
    },
    {
        id: 'name_master',
        name: 'AI 取名大师',
        desc: '为宝宝/品牌/宠物/小说角色起名。结合五行、寓意、音韵分析，给出详细的命名解读。',
        href: 'tools/word_playground/name_master.html',
        icon: 'fa-solid fa-signature',
        category: 'word_playground',
        tags: ['小红书'],
        isNew: true,
        complexity: 2,
        iconBg: 'bg-emerald-50',
        iconColor: 'text-emerald-600',
        borderColor: 'emerald-200',
        hoverTextColor: 'text-emerald-600',
        linkColor: 'text-emerald-600'
    },
    {
        id: 'rap_generator',
        name: 'AI 说唱生成器',
        desc: '输入主题，AI 生成押韵的中文说唱歌词，标注韵脚和 Flow 节奏。支持 Freestyle/Old School/Trap 风格。',
        href: 'tools/word_playground/rap_generator.html',
        icon: 'fa-solid fa-microphone-lines',
        category: 'word_playground',
        tags: ['抖音', '短视频'],
        isNew: true,
        complexity: 2,
        iconBg: 'bg-purple-50',
        iconColor: 'text-purple-600',
        borderColor: 'purple-200',
        hoverTextColor: 'text-purple-600',
        linkColor: 'text-purple-600'
    },
    {
        id: 'wuxia_character',
        name: '武侠/仙侠人设生成器',
        desc: '回答几个问题，AI 为你生成完整的武侠人设：名号、门派、武功、性格、命运线和专属故事。',
        href: 'tools/word_playground/wuxia_character.html',
        icon: 'fa-solid fa-yin-yang',
        category: 'word_playground',
        tags: ['小红书', '短视频'],
        isNew: true,
        complexity: 2,
        iconBg: 'bg-slate-50',
        iconColor: 'text-slate-600',
        borderColor: 'slate-200',
        hoverTextColor: 'text-slate-600',
        linkColor: 'text-slate-600'
    }
];
