window.toolCollections = window.toolCollections || {};
window.toolCollections.creative = [
    { id: 'bedtime_stories', name: '睡前故事生成器', desc: '专属童话定制。输入孩子名字和想教育的道理，生成独一无二的奇幻梦境故事。', href: 'tools/creative/bedtime_stories.html',         icon: 'fa-solid fa-moon', category: 'creative', tags: ['亲子', '创意'], isNew: true, iconBg: 'bg-indigo-900', iconColor: 'text-indigo-300', borderColor: 'indigo-800', hoverTextColor: 'text-indigo-300', linkColor: 'text-indigo-300' },
    { id: 'wish_future_card', name: '一句话愿望 + 未来签', desc: '写下愿望，生成可保存的未来签卡片。', href: 'tools/creative/wish_future_card.html',         icon: 'fa-solid fa-wand-magic-sparkles', category: 'creative', tags: ['生活', '仪式感'], isNew: true, iconBg: 'bg-yellow-50', iconColor: 'text-yellow-600', borderColor: 'yellow-200', hoverTextColor: 'text-yellow-600', linkColor: 'text-yellow-600', badgeStyle: 'bg-yellow-100 text-yellow-700' },
    { id: 'energy_recipe', name: '今日能量配方', desc: '输入状态、天气与重点，一键生成带仪式感的生活与工作配方卡。', href: 'tools/creative/energy_recipe.html', icon: 'fa-solid fa-sun', category: 'creative', tags: ['生活', '仪式感'], isNew: true, iconBg: 'bg-indigo-50', iconColor: 'text-indigo-600', borderColor: 'indigo-200', hoverTextColor: 'text-indigo-600', linkColor: 'text-indigo-600', badgeStyle: 'bg-indigo-100 text-indigo-700' },
    { id: 'done_list', name: '反向待办 Done List', desc: '写下完成的小事，生成轻治愈鼓励卡片。', href: 'tools/creative/done_list.html', icon: 'fa-solid fa-check-circle', category: 'creative', tags: ['生活', '治愈'], isNew: true, iconBg: 'bg-emerald-50', iconColor: 'text-emerald-600', borderColor: 'emerald-200', hoverTextColor: 'text-emerald-600', linkColor: 'text-emerald-600', badgeStyle: 'bg-emerald-100 text-emerald-700' },
    { id: 'flow_starter', name: '15 分钟心流启动器', desc: '引导式仪式 + 倒计时，帮你快速进入专注。', href: 'tools/creative/flow_starter.html',         icon: 'fa-solid fa-bolt', category: 'creative', tags: ['专注', '效率'], isNew: true, iconBg: 'bg-sky-50', iconColor: 'text-sky-600', borderColor: 'sky-200', hoverTextColor: 'text-sky-600', linkColor: 'text-sky-600', badgeStyle: 'bg-sky-100 text-sky-700' },
    { id: 'mood_weather', name: '情绪天气预报', desc: '用滑杆生成动态天空与今日心情天气。', href: 'tools/creative/mood_weather.html', icon: 'fa-solid fa-cloud-sun', category: 'creative', tags: ['情绪', '可视化'], isNew: true, iconBg: 'bg-blue-50', iconColor: 'text-blue-600', borderColor: 'blue-200', hoverTextColor: 'text-blue-600', linkColor: 'text-blue-600', badgeStyle: 'bg-blue-100 text-blue-700' },
    { id: 'tarot_divination', name: 'AI 塔罗占卜馆', desc: '沉浸式神秘学体验。洗牌、抽牌、解牌全流程。AI 结合牌面与你的问题进行深度灵性解读。', href: 'tools/creative/tarot_divination.html', icon: 'fa-solid fa-wand-magic-sparkles', category: 'creative', tags: ['趣味', '玄学'], isNew: true, iconBg: 'bg-purple-900', iconColor: 'text-purple-300', borderColor: 'purple-800', hoverTextColor: 'text-purple-300', linkColor: 'text-purple-300', badgeStyle: 'bg-purple-800 text-purple-100' },
    { id: 'travel_mini_map', name: '旅行迷你地图', desc: '旅行足迹可视化。输入去过的城市或计划的路线，生成可交互的迷你地图，标注打卡点与心情记录。', href: 'tools/creative/travel_mini_map.html', icon: 'fa-solid fa-map', category: 'creative', tags: ['旅行', '可视化'], isNew: true, iconBg: 'bg-emerald-50', iconColor: 'text-emerald-600', borderColor: 'emerald-200', hoverTextColor: 'text-emerald-600', linkColor: 'text-emerald-600', badgeStyle: 'bg-emerald-100 text-emerald-700' },
    { id: 'bookofanswer', name: '答案之书', desc: '沉浸式神秘学体验。在心中默念疑惑，随机翻开一张卡片获取指引。精美星空动画，翻牌特效。', href: 'tools/creative/bookofanswer.html', icon: 'fa-solid fa-book-open', category: 'creative', tags: ['趣味', '玄学'], isNew: true, iconBg: 'bg-indigo-900', iconColor: 'text-indigo-300', borderColor: 'indigo-800', hoverTextColor: 'text-indigo-300', linkColor: 'text-indigo-300', badgeStyle: 'bg-indigo-800 text-indigo-100' },
    { id: 'meme_generator', name: '表情包制作器', desc: 'AI趣味创作助手。快速制作搞笑表情包，支持多种模板和自定义文字，一键生成分享。', href: 'tools/creative/meme_generator.html', icon: 'fa-solid fa-smile', category: 'creative', tags: ['趣味', '创意'], isNew: true, iconBg: 'bg-yellow-50', iconColor: 'text-yellow-600', borderColor: 'yellow-200', hoverTextColor: 'text-yellow-600', linkColor: 'text-yellow-600', badgeStyle: 'bg-yellow-100 text-yellow-700' },
];
