window.toolCollections = window.toolCollections || {};
window.toolCollections.ai_lab = [
    {
        id: 'ai_debate',
        name: 'AI 辩论赛',
        desc: '选一个话题，AI 自动生成正反两方激烈辩论。你来当裁判，看谁更有说服力！',
        href: 'tools/ai_lab/ai_debate.html',
        icon: 'fa-solid fa-comments',
        category: 'ai_lab',
        tags: [],
        isNew: true,
        complexity: 2,
        iconBg: 'bg-rose-50',
        iconColor: 'text-rose-600',
        borderColor: 'rose-200',
        hoverTextColor: 'text-rose-600',
        linkColor: 'text-rose-600'
    },
    {
        id: 'parallel_universe',
        name: '平行宇宙生成器',
        desc: '描述你人生中的一个关键选择，AI 为你生成 3 条截然不同的平行宇宙人生线。',
        href: 'tools/ai_lab/parallel_universe.html',
        icon: 'fa-solid fa-atom',
        category: 'ai_lab',
        tags: [],
        isNew: true,
        complexity: 2,
        iconBg: 'bg-violet-50',
        iconColor: 'text-violet-600',
        borderColor: 'violet-200',
        hoverTextColor: 'text-violet-600',
        linkColor: 'text-violet-600'
    },
    {
        id: 'life_simulator',
        name: 'AI 人生模拟器',
        desc: '文字版人生模拟游戏。每一步做出选择，AI 模拟后续发展，看看你的人生会走向何方。',
        href: 'tools/ai_lab/life_simulator.html',
        icon: 'fa-solid fa-gamepad',
        category: 'ai_lab',
        tags: [],
        isNew: true,
        complexity: 2,
        iconBg: 'bg-emerald-50',
        iconColor: 'text-emerald-600',
        borderColor: 'emerald-200',
        hoverTextColor: 'text-emerald-600',
        linkColor: 'text-emerald-600'
    },
    {
        id: 'what_if',
        name: '"如果…会怎样" 思维实验',
        desc: '提出一个脑洞大开的 "如果" 问题，AI 用科学和想象力帮你推演出完整的蝴蝶效应链。',
        href: 'tools/ai_lab/what_if.html',
        icon: 'fa-solid fa-wand-sparkles',
        category: 'ai_lab',
        tags: [],
        isNew: true,
        complexity: 2,
        iconBg: 'bg-amber-50',
        iconColor: 'text-amber-600',
        borderColor: 'amber-200',
        hoverTextColor: 'text-amber-600',
        linkColor: 'text-amber-600'
    },
    {
        id: 'time_travel_guide',
        name: 'AI 穿越指南',
        desc: '选择一个历史时代，AI 为你生成一份完整的穿越生存手册：身份、技能、避坑、发家致富攻略。',
        href: 'tools/ai_lab/time_travel_guide.html',
        icon: 'fa-solid fa-clock-rotate-left',
        category: 'ai_lab',
        tags: [],
        isNew: true,
        complexity: 2,
        iconBg: 'bg-sky-50',
        iconColor: 'text-sky-600',
        borderColor: 'sky-200',
        hoverTextColor: 'text-sky-600',
        linkColor: 'text-sky-600'
    }
];
