window.toolCollections = window.toolCollections || {};
window.toolCollections.worker_survival = [
    {
        id: 'boss_translator',
        name: '老板画饼翻译机',
        desc: '输入老板/HR 的话，AI 秒翻成大实话。"弹性工作制" = "24小时待命无偿加班"',
        href: 'tools/worker_survival/boss_translator.html',
        icon: 'fa-solid fa-language',
        category: 'worker_survival',
        tags: [],
        isNew: true,
        complexity: 1,
        iconBg: 'bg-orange-50',
        iconColor: 'text-orange-600',
        borderColor: 'orange-200',
        hoverTextColor: 'text-orange-600',
        linkColor: 'text-orange-600'
    },
    {
        id: 'poop_calculator',
        name: '带薪拉屎计算器',
        desc: '根据月薪计算你蹲坑赚了多少钱，结束后 AI 写一篇气势磅礴的"如厕赋"',
        href: 'tools/worker_survival/poop_calculator.html',
        icon: 'fa-solid fa-stopwatch',
        category: 'worker_survival',
        tags: [],
        isNew: true,
        complexity: 1,
        iconBg: 'bg-yellow-50',
        iconColor: 'text-yellow-600',
        borderColor: 'yellow-200',
        hoverTextColor: 'text-yellow-600',
        linkColor: 'text-yellow-600'
    },
    {
        id: 'weekly_inflator',
        name: '周报吹水扩写器',
        desc: '输入几个干瘪关键词，AI 帮你扩成结构完美、工作量爆满的周报',
        href: 'tools/worker_survival/weekly_inflator.html',
        icon: 'fa-solid fa-file-lines',
        category: 'worker_survival',
        tags: [],
        isNew: true,
        complexity: 1,
        iconBg: 'bg-blue-50',
        iconColor: 'text-blue-600',
        borderColor: 'blue-200',
        hoverTextColor: 'text-blue-600',
        linkColor: 'text-blue-600'
    },
    {
        id: 'excuse_generator',
        name: '请假借口生成器',
        desc: '根据天气、星期几和你的岗位，AI 编造一个合情合理且难以拆穿的请假理由',
        href: 'tools/worker_survival/excuse_generator.html',
        icon: 'fa-solid fa-bed',
        category: 'worker_survival',
        tags: [],
        isNew: true,
        complexity: 1,
        iconBg: 'bg-green-50',
        iconColor: 'text-green-600',
        borderColor: 'green-200',
        hoverTextColor: 'text-green-600',
        linkColor: 'text-green-600'
    },
    {
        id: 'jd_scanner',
        name: 'JD 避雷扫描仪',
        desc: '粘贴招聘要求，AI 计算"牛马指数"和"强制加班概率"，识别黑话避坑',
        href: 'tools/worker_survival/jd_scanner.html',
        icon: 'fa-solid fa-shield-halved',
        category: 'worker_survival',
        tags: [],
        isNew: true,
        complexity: 2,
        iconBg: 'bg-red-50',
        iconColor: 'text-red-600',
        borderColor: 'red-200',
        hoverTextColor: 'text-red-600',
        linkColor: 'text-red-600'
    }
];
