window.toolCollections = window.toolCollections || {};
window.toolCollections.topic = [
    { id: 'xhs_generator', name: '爆款选题专家', desc: '输入主题和人群，批量生成具有点击欲的选题卡片。支持可视化预览、单篇生成及批量导出。', href: 'tools/topic/xhs_generator.html', icon: 'fa-solid fa-table-cells', category: 'topic', tags: ['小红书'], isNew: false, iconBg: 'bg-red-50', iconColor: 'text-red-600', borderColor: 'red-200', hoverTextColor: 'text-red-600', linkColor: 'text-red-600' },
    { id: 'viral_title_generator', name: '爆款标题实验室', desc: '输入内容，AI 自动生成 10-20 个多维度爆款标题（悬念、痛点、情绪等），并预测点击率得分。', href: 'tools/topic/viral_title_generator.html', icon: 'fa-solid fa-flask', category: 'topic', tags: ['小红书', '短视频', '公众号'], isNew: true, iconBg: 'bg-violet-50', iconColor: 'text-violet-600', borderColor: 'violet-200', hoverTextColor: 'text-violet-600', linkColor: 'text-violet-600', badgeStyle: 'bg-violet-100 text-violet-700' },
    { id: 'creative_storm', name: '创意风暴', desc: '沉浸式灵感激发工具。输入想法，AI 生成的文案如雨般落下或在风中重组，提供独特的视觉化创作体验。', href: 'tools/topic/creative_storm.html', icon: 'fa-solid fa-bolt', category: 'topic', tags: ['小红书', '短视频', '公众号'], isNew: true, iconBg: 'bg-violet-50', iconColor: 'text-violet-600', borderColor: 'violet-200', hoverTextColor: 'text-violet-600', linkColor: 'text-violet-600', badgeStyle: 'bg-violet-100 text-violet-700' },
    { id: 'content_calendar_planner', name: '智能内容日历规划师', desc: '策略型规划工具。自定义周期和频率，AI 自动生成可视化的内容排期日历，并支持单篇文案的一键生成与导出。', href: 'tools/topic/content_calendar_planner.html', icon: 'fa-solid fa-calendar-days', category: 'topic', tags: ['小红书', '短视频', '公众号'], isNew: true, iconBg: 'bg-blue-50', iconColor: 'text-blue-600', borderColor: 'blue-200', hoverTextColor: 'text-blue-600', linkColor: 'text-blue-600' },
    { id: 'course_planner', name: '知识付费课程策划', desc: '想做课但没思路？一键生成课程大纲、每节课卖点及朋友圈宣发文案。', href: 'tools/topic/course_planner.html',         icon: 'fa-solid fa-graduation-cap', category: 'topic', tags: ['私域', '知识付费'], isNew: true, iconBg: 'bg-indigo-50', iconColor: 'text-indigo-600', borderColor: 'indigo-200', hoverTextColor: 'text-indigo-600', linkColor: 'text-indigo-600' },
    { id: 'holiday_copywriter', name: '节日节气文案生成器', desc: '24节气+传统节日+现代节日全覆盖。支持小红书/公众号/朋友圈等多平台，抒情/促销/互动多种风格，可植入品牌产品。', href: 'tools/topic/holiday_copywriter.html',         icon: 'fa-solid fa-calendar', category: 'topic', tags: ['小红书', '公众号', '短视频', '私域'], isNew: true, iconBg: 'bg-red-50', iconColor: 'text-red-600', borderColor: 'red-200', hoverTextColor: 'text-red-600', linkColor: 'text-red-600', badgeStyle: 'bg-red-100 text-red-700' },
    { id: 'trending_topic_tracker', name: '热点追踪与选题推荐', desc: '内容运营神器。实时追踪各平台热点话题，AI智能推荐相关选题和创作角度。', href: 'tools/topic/trending_topic_tracker.html', icon: 'fa-solid fa-trending-up', category: 'topic', tags: ['小红书', '短视频', '公众号'], isNew: true, iconBg: 'bg-red-50', iconColor: 'text-red-600', borderColor: 'red-200', hoverTextColor: 'text-red-600', linkColor: 'text-red-600', badgeStyle: 'bg-red-100 text-red-700' },
    { id: 'hotspot_dashboard', name: '多平台热点看板', desc: '抖音、快手、小红书、B站、微博热点并排展示，可配置数据源与自动刷新。', href: 'tools/topic/hotspot_dashboard.html', icon: 'fa-solid fa-fire', category: 'topic', tags: ['抖音', '快手', '小红书', 'B站', '微博', '短视频'], isNew: true, iconBg: 'bg-cyan-50', iconColor: 'text-cyan-600', borderColor: 'cyan-200', hoverTextColor: 'text-cyan-600', linkColor: 'text-cyan-600', badgeStyle: 'bg-cyan-100 text-cyan-700' },
];
