window.toolCollections = window.toolCollections || {};
window.toolCollections.biz_analysis = [
    {
        id: 'business_plan',
        name: '商业计划书生成器',
        desc: '商业创意→商业模式画布→市场分析→竞争分析→财务预测→完整BP，融资立项必备。',
        href: 'tools/biz_analysis/business_plan.html',
        icon: 'fa-solid fa-file-invoice',
        category: 'biz_analysis',
        tags: ['职场'],
        isNew: true,
        complexity: 5,
        iconBg: 'bg-indigo-50',
        iconColor: 'text-indigo-600',
        borderColor: 'indigo-200',
        hoverTextColor: 'text-indigo-600',
        linkColor: 'text-indigo-600'
    },
    {
        id: 'pricing_strategy',
        name: '定价策略分析师',
        desc: '产品信息+竞品价格→成本加成/竞争/价值定价模型分析→推荐价格区间+定价话术。',
        href: 'tools/biz_analysis/pricing_strategy.html',
        icon: 'fa-solid fa-tags',
        category: 'biz_analysis',
        tags: ['电商'],
        isNew: true,
        complexity: 4,
        iconBg: 'bg-emerald-50',
        iconColor: 'text-emerald-600',
        borderColor: 'emerald-200',
        hoverTextColor: 'text-emerald-600',
        linkColor: 'text-emerald-600'
    },
    {
        id: 'feedback_analyzer',
        name: '用户反馈分析器',
        desc: '批量粘贴用户评论→自动分类+情感分析→提炼核心诉求→改进优先级矩阵+行动计划。',
        href: 'tools/biz_analysis/feedback_analyzer.html',
        icon: 'fa-solid fa-comments',
        category: 'biz_analysis',
        tags: ['电商', '小红书'],
        isNew: true,
        complexity: 3,
        iconBg: 'bg-orange-50',
        iconColor: 'text-orange-600',
        borderColor: 'orange-200',
        hoverTextColor: 'text-orange-600',
        linkColor: 'text-orange-600'
    },
    {
        id: 'competitor_report',
        name: '竞品分析报告',
        desc: '输入竞品信息→产品/定价/渠道/口碑结构化分析→对比矩阵→差异化策略建议。',
        href: 'tools/biz_analysis/competitor_report.html',
        icon: 'fa-solid fa-chart-bar',
        category: 'biz_analysis',
        tags: ['职场'],
        isNew: true,
        complexity: 4,
        iconBg: 'bg-blue-50',
        iconColor: 'text-blue-600',
        borderColor: 'blue-200',
        hoverTextColor: 'text-blue-600',
        linkColor: 'text-blue-600'
    },
    {
        id: 'feasibility_assessment',
        name: '项目可行性评估',
        desc: '项目描述+资源约束→PEST+SWOT+五力分析→风险评估矩阵→可行性结论+建议。',
        href: 'tools/biz_analysis/feasibility_assessment.html',
        icon: 'fa-solid fa-clipboard-check',
        category: 'biz_analysis',
        tags: ['职场'],
        isNew: true,
        complexity: 5,
        iconBg: 'bg-teal-50',
        iconColor: 'text-teal-600',
        borderColor: 'teal-200',
        hoverTextColor: 'text-teal-600',
        linkColor: 'text-teal-600'
    }
];
